// Generated by scripts/generate-cav-loca-level.mjs from
// nethack-c/upstream/dat/Cav-loca.lua. Do not edit by hand.

export const CAV_LOCA_LEVEL_MAP = Object.freeze([
    "                                                                            ",
    "    .............                     ...........                           ",
    "   ...............                   .............                          ",
    "    .............                  ...............        ..........        ",
    "     ...........                    .............      ...............      ",
    "        ...                                    ...   ..................     ",
    "         ...                ..........          ... ..................      ",
    "          ...              ............          BBB...................     ",
    "           ...              ..........          ......................      ",
    "            .....                 ..      .....B........................    ",
    "  ....       ...............      .    ........B..........................  ",
    " ......     .. .............S..............         ..................      ",
    "  ....     ..                ...........             ...............        ",
    "     ..  ...                                    ....................        ",
    "      ....                                      BB...................       ",
    "         ..                 ..                 ..  ...............          ",
    "          ..   .......     ....  .....  ....  ..     .......   S            ",
    "           ............     ....... ..  .......       .....    ...  ....    ",
    "               .......       .....   ......                      .......    ",
    "                                                                            "
]);

export const CAV_LOCA_MONSTERS = Object.freeze([
    {
        "id": "bugbear",
        "x": 2,
        "y": 10,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 3,
        "y": 11,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 4,
        "y": 12,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 2,
        "y": 11,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 16,
        "y": 16,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 17,
        "y": 17,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 18,
        "y": 18,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 19,
        "y": 16,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 30,
        "y": 6,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 31,
        "y": 7,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 32,
        "y": 8,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 33,
        "y": 6,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "x": 34,
        "y": 7,
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "peaceful": 0
    },
    {
        "id": "bugbear",
        "peaceful": 0
    },
    {
        "class": "h",
        "peaceful": 0
    },
    {
        "class": "H",
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "x": 3,
        "y": 12,
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "x": 20,
        "y": 17,
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "x": 35,
        "y": 8,
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "peaceful": 0
    },
    {
        "id": "hill giant",
        "peaceful": 0
    },
    {
        "class": "H",
        "peaceful": 0
    }
]);
