// Generated by scripts/generate-config-statements.mjs. Do not edit.
// Source: NetHack 5.0 src/cfgfiles.c config_line_stmt[], at
// 16ff59115315917b93185d026aeefea06db9b0f4.

// Player configuration reads skip syscnf_only rows. The source build also
// selects conditional rows before this table is generated.
export const configLineStatements = Object.freeze([
    { name: 'options', minLength: 4 },
    { name: 'autopickup_exception', minLength: 5 },
    { name: 'bindings', minLength: 4 },
    { name: 'autocomplete', minLength: 5 },
    { name: 'msgtype', minLength: 7 },
    { name: 'hackdir', minLength: 4 },
    { name: 'leveldir', minLength: 4 },
    { name: 'levels', minLength: 4 },
    { name: 'savedir', minLength: 4 },
    { name: 'bonesdir', minLength: 5 },
    { name: 'datadir', minLength: 4 },
    { name: 'scoredir', minLength: 4 },
    { name: 'lockdir', minLength: 4 },
    { name: 'configdir', minLength: 4 },
    { name: 'troubledir', minLength: 4 },
    { name: 'name', minLength: 4 },
    { name: 'role', minLength: 4 },
    { name: 'character', minLength: 4 },
    { name: 'dogname', minLength: 3 },
    { name: 'catname', minLength: 3 },
    { name: 'boulder', minLength: 3 },
    { name: 'menucolor', minLength: 9 },
    { name: 'hilite_status', minLength: 6 },
    { name: 'warnings', minLength: 5 },
    { name: 'roguesymbols', minLength: 4 },
    { name: 'symbols', minLength: 4 },
    { name: 'wizkit', minLength: 6 },
    { name: 'qt_tilewidth', minLength: 12 },
    { name: 'qt_tileheight', minLength: 13 },
    { name: 'qt_fontsize', minLength: 11 },
    { name: 'qt_compact', minLength: 10 },
].map(Object.freeze));
