// Generated by scripts/generate-earth-level.mjs from
// nethack-c/upstream/dat/earth.lua. Do not edit by hand.

export const EARTH_LEVEL_MAP = Object.freeze([
    "                                                                            ",
    "  ...                                                                       ",
    " ....                ..                                                     ",
    " .....             ...                                      ..              ",
    "  ....              ....                                     ...            ",
    "   ....              ...                ....                 ...      .     ",
    "    ..                ..              .......                 .      ..     ",
    "                                      ..  ...                        .      ",
    "              .                      ..    .                         ...    ",
    "             ..  ..                  .     ..                         .     ",
    "            ..   ...                        .                               ",
    "            ...   ...                                                       ",
    "              .. ...                                 ..                     ",
    "               ....                                 ..                      ",
    "                          ..                                       ...      ",
    "                         ..                                       .....     ",
    "  ...                                                              ...      ",
    " ....                                                                       ",
    "   ..                                                                       ",
    "                                                                            "
]);

export const EARTH_MONSTERS = Object.freeze([
    {
        "form": "named-at-coordinate",
        "id": "Elvenking",
        "x": 67,
        "y": 16
    },
    {
        "form": "named-at-coordinate",
        "id": "minotaur",
        "x": 67,
        "y": 14
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 52,
        "y": 13,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 53,
        "y": 13,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 53,
        "y": 12
    },
    {
        "form": "named-at-coordinate",
        "id": "stone giant",
        "x": 54,
        "y": 12
    },
    {
        "form": "named-at-coordinate",
        "id": "pit viper",
        "x": 70,
        "y": 5
    },
    {
        "form": "named-at-coordinate",
        "id": "barbed devil",
        "x": 69,
        "y": 6
    },
    {
        "form": "named-at-coordinate",
        "id": "stone giant",
        "x": 69,
        "y": 8
    },
    {
        "form": "named-at-coordinate",
        "id": "stone golem",
        "x": 71,
        "y": 8
    },
    {
        "form": "named-at-coordinate",
        "id": "pit fiend",
        "x": 70,
        "y": 9
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 70,
        "y": 8,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 60,
        "y": 3,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "stone giant",
        "x": 61,
        "y": 4
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 62,
        "y": 4,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 61,
        "y": 5,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "scorpion",
        "x": 62,
        "y": 5
    },
    {
        "form": "named-at-coordinate",
        "id": "rock piercer",
        "x": 63,
        "y": 5
    },
    {
        "form": "named-at-coordinate",
        "id": "umber hulk",
        "x": 40,
        "y": 5
    },
    {
        "form": "named-at-coordinate",
        "id": "dust vortex",
        "x": 42,
        "y": 5
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 38,
        "y": 6
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 39,
        "y": 6,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 41,
        "y": 6,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 38,
        "y": 7,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "stone giant",
        "x": 39,
        "y": 7
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 43,
        "y": 7,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "stone golem",
        "x": 37,
        "y": 8
    },
    {
        "form": "named-at-coordinate",
        "id": "pit viper",
        "x": 43,
        "y": 8
    },
    {
        "form": "named-at-coordinate",
        "id": "pit viper",
        "x": 43,
        "y": 9
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 44,
        "y": 10
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 2,
        "y": 1,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 3,
        "y": 1,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "stone golem",
        "x": 1,
        "y": 2
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 2,
        "y": 2,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 4,
        "y": 3
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 3,
        "y": 3
    },
    {
        "form": "named-at-coordinate",
        "id": "pit fiend",
        "x": 3,
        "y": 4
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 4,
        "y": 5,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "pit viper",
        "x": 5,
        "y": 6
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 21,
        "y": 2,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 21,
        "y": 3,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "minotaur",
        "x": 21,
        "y": 4
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 21,
        "y": 5,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 22,
        "y": 5
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 22,
        "y": 6,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 23,
        "y": 6,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "pit viper",
        "x": 14,
        "y": 8
    },
    {
        "form": "named-at-coordinate",
        "id": "barbed devil",
        "x": 14,
        "y": 9
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 13,
        "y": 10,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 12,
        "y": 11
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 14,
        "y": 12,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 15,
        "y": 13,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "stone giant",
        "x": 17,
        "y": 13
    },
    {
        "form": "named-at-coordinate",
        "id": "stone golem",
        "x": 18,
        "y": 13
    },
    {
        "form": "named-at-coordinate",
        "id": "pit fiend",
        "x": 18,
        "y": 12
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 18,
        "y": 11,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 18,
        "y": 10,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "barbed devil",
        "x": 2,
        "y": 16
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 3,
        "y": 16,
        "peaceful": 0
    },
    {
        "form": "named-at-coordinate",
        "id": "rock troll",
        "x": 2,
        "y": 17
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 4,
        "y": 17,
        "peaceful": 0
    },
    {
        "form": "table",
        "id": "earth elemental",
        "x": 4,
        "y": 18,
        "peaceful": 0
    }
]);
