// Generated by scripts/generate-hea-loca-level.mjs from
// nethack-c/upstream/dat/Hea-loca.lua. Do not edit by hand.

export const HEA_LOCA_LEVEL_MAP = Object.freeze([
    "PPPPPPPPPPPPP.......PPPPPPPPPPP",
    "PPPPPPPP...............PPPPPPPP",
    "PPPP.....-------------...PPPPPP",
    "PPPPP....|.S.........|....PPPPP",
    "PPP......+.|.........|...PPPPPP",
    "PPP......+.|.........|..PPPPPPP",
    "PPPP.....|.S.........|..PPPPPPP",
    "PPPPP....-------------....PPPPP",
    "PPPPPPPP...............PPPPPPPP",
    "PPPPPPPPPPP........PPPPPPPPPPPP"
]);
