// Generated by scripts/generate-hea-goal-level.mjs from
// nethack-c/upstream/dat/Hea-goal.lua. Do not edit by hand.

export const HEA_GOAL_LEVEL_MAP = Object.freeze([
    ".P....................................PP.",
    "PP.......PPPPPPP....PPPPPPP....PPPP...PP.",
    "...PPPPPPP....PPPPPPP.....PPPPPP..PPP...P",
    "...PP..............................PPP...",
    "..PP..............................PP.....",
    "..PP..............................PPP....",
    "..PPP..............................PP....",
    ".PPP..............................PPPP...",
    "...PP............................PPP...PP",
    "..PPPP...PPPPP..PPPP...PPPPP.....PP...PP.",
    "P....PPPPP...PPPP..PPPPP...PPPPPPP...PP..",
    "PPP..................................PPP."
]);
