// Generated by scripts/generate-kni-loca-level.mjs from
// nethack-c/upstream/dat/Kni-loca.lua. Do not edit by hand.

export const KNI_LOCA_LEVEL_MAP = Object.freeze([
    "xxxxxxxxx......xxxx...........xxxxxxxxxx",
    "xxxxxxx.........xxx.............xxxxxxxx",
    "xxxx..............................xxxxxx",
    "xx.................................xxxxx",
    "....................................xxxx",
    ".......................................x",
    "........................................",
    "xx...................................xxx",
    "xxxx..............................xxxxxx",
    "xxxxxx..........................xxxxxxxx",
    "xxxxxxxx.........xx..........xxxxxxxxxxx",
    "xxxxxxxxx.......xxxxxx.....xxxxxxxxxxxxx"
]);

export const KNI_LOCA_FIXED_TRAPS = Object.freeze([
    {
        "type": "magic",
        "x": 8,
        "y": 11
    },
    {
        "type": "magic",
        "x": 9,
        "y": 11
    },
    {
        "type": "magic",
        "x": 10,
        "y": 11
    },
    {
        "type": "magic",
        "x": 11,
        "y": 11
    },
    {
        "type": "magic",
        "x": 12,
        "y": 11
    },
    {
        "type": "magic",
        "x": 13,
        "y": 11
    },
    {
        "type": "magic",
        "x": 14,
        "y": 11
    },
    {
        "type": "magic",
        "x": 15,
        "y": 11
    },
    {
        "type": "magic",
        "x": 16,
        "y": 11
    },
    {
        "type": "magic",
        "x": 20,
        "y": 11
    },
    {
        "type": "magic",
        "x": 21,
        "y": 11
    },
    {
        "type": "magic",
        "x": 22,
        "y": 11
    },
    {
        "type": "magic",
        "x": 23,
        "y": 11
    },
    {
        "type": "magic",
        "x": 24,
        "y": 11
    },
    {
        "type": "magic",
        "x": 25,
        "y": 11
    },
    {
        "type": "magic",
        "x": 26,
        "y": 11
    },
    {
        "type": "magic",
        "x": 27,
        "y": 11
    },
    {
        "type": "magic",
        "x": 28,
        "y": 11
    },
    {
        "type": "magic",
        "x": 0,
        "y": 3
    },
    {
        "type": "magic",
        "x": 0,
        "y": 4
    },
    {
        "type": "magic",
        "x": 0,
        "y": 5
    },
    {
        "type": "magic",
        "x": 0,
        "y": 6
    },
    {
        "type": "magic",
        "x": 6,
        "y": 0
    },
    {
        "type": "magic",
        "x": 7,
        "y": 0
    },
    {
        "type": "magic",
        "x": 8,
        "y": 0
    },
    {
        "type": "magic",
        "x": 9,
        "y": 0
    },
    {
        "type": "magic",
        "x": 10,
        "y": 0
    },
    {
        "type": "magic",
        "x": 11,
        "y": 0
    },
    {
        "type": "magic",
        "x": 12,
        "y": 0
    },
    {
        "type": "magic",
        "x": 13,
        "y": 0
    },
    {
        "type": "magic",
        "x": 14,
        "y": 0
    },
    {
        "type": "magic",
        "x": 19,
        "y": 0
    },
    {
        "type": "magic",
        "x": 20,
        "y": 0
    },
    {
        "type": "magic",
        "x": 21,
        "y": 0
    },
    {
        "type": "magic",
        "x": 22,
        "y": 0
    },
    {
        "type": "magic",
        "x": 23,
        "y": 0
    },
    {
        "type": "magic",
        "x": 24,
        "y": 0
    },
    {
        "type": "magic",
        "x": 25,
        "y": 0
    },
    {
        "type": "magic",
        "x": 26,
        "y": 0
    },
    {
        "type": "magic",
        "x": 27,
        "y": 0
    },
    {
        "type": "magic",
        "x": 28,
        "y": 0
    },
    {
        "type": "magic",
        "x": 29,
        "y": 0
    },
    {
        "type": "magic",
        "x": 30,
        "y": 0
    },
    {
        "type": "magic",
        "x": 31,
        "y": 0
    },
    {
        "type": "magic",
        "x": 32,
        "y": 0
    }
]);

export const KNI_LOCA_MONSTERS = Object.freeze([
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "id": "quasit",
        "peaceful": 0
    },
    {
        "class": "i",
        "peaceful": 0
    },
    {
        "class": "j",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "id": "ochre jelly",
        "peaceful": 0
    },
    {
        "class": "j",
        "peaceful": 0
    }
]);
