// mdlib.js -- Runtime build-option text.
// C ref: mdlib.c build_savebones_compat_string(), opt_out_words(),
// build_options(), runtime_info_init(), and do_runtime_info().

const OPTION_INDENT = '    ';
const OPTION_WRAP_COLUMN = 75; // C: COLNO - 5 with the 80-column map.

// The recorder's config.h and Unix hints select these mdlib.c build_opts[]
// entries. Punctuation is added after conditional filtering, as in C.
const RECORDER_BUILD_OPTIONS = Object.freeze([
    'I32LP64 data model',
    'color',
    'data file compression',
    'deferred handling of hangup signal',
    'insurance files for recovering from crashes',
    'live logging support',
    'log file',
    'extended log file',
    'errors and warnings log file',
    'mail daemon',
    'news file',
    'internal pager used for viewing help files',
    'pattern matching via :PATMATCH:',
    'pseudo random numbers generated by ISAAC64',
    'strong PRNG seed from /dev/random',
    'restore saved games via menu',
    'screen clipping',
    'shell command',
    'traditional status display',
    'status via windowport with highlighting',
    'suspend command',
    'terminal info library',
    'system configuration at run-time',
    'show stack trace on error',
    'launch browser to report issues',
    'save and bones files accepted from version 5.0.0 only',
    'and basic NetHack features',
]);

function wrapWords(phrases) {
    const lines = [];
    let line = OPTION_INDENT;
    for (const phrase of phrases) {
        for (const word of phrase.split(' ')) {
            // C tests the word against the current length before it appends
            // the separating space, so a completed line can reach column 76.
            if (line.length + word.length > OPTION_WRAP_COLUMN) {
                lines.push(line);
                line = OPTION_INDENT;
            }
            line += `${line === OPTION_INDENT ? '' : ' '}${word}`;
        }
    }
    lines.push(line);
    return lines;
}

function punctuatedBuildOptions() {
    return RECORDER_BUILD_OPTIONS.map((option, index) => {
        const suffix = index === RECORDER_BUILD_OPTIONS.length - 1 ? '.' : ',';
        return `${option}${suffix}`;
    });
}

// C ref: mdlib.c build_options(). Blank entries are retained because
// version.c uses the following outdented header to insert each separator.
export function build_options() {
    return [
        '',
        `${OPTION_INDENT}NetHack version 5.0.0`,
        'Options compiled into this edition:',
        '',
        ...wrapWords(punctuatedBuildOptions()),
        '',
        'Supported windowing system:',
        '',
        ...wrapWords([
            '"tty" (traditional text with optional line-drawing).',
        ]),
        '',
        'Supported soundlib:',
        '',
        ...wrapWords(['"nosound".']),
        '',
        "NetHack 5.0.* uses the 'Lua' interpreter to process some data:",
        '',
        '    :LUACOPYRIGHT:',
        '',
        '    "Permission is hereby granted, free of charge, to any person obtaining',
        '     a copy of this software and associated documentation files (the',
        '     "Software"), to deal in the Software without restriction including',
        '     without limitation the rights to use, copy, modify, merge, publish,',
        '     distribute, sublicense, and/or sell copies of the Software, and to',
        '     permit persons to whom the Software is furnished to do so, subject to',
        '     the following conditions:',
        '     The above copyright notice and this permission notice shall be',
        '     included in all copies or substantial portions of the Software."',
        '',
    ];
}

export function runtime_info_init() {
    return build_options();
}

export function do_runtime_info(runtimeLines, context) {
    return context.index < runtimeLines.length
        ? runtimeLines[context.index++] : null;
}
