// Generated by scripts/generate-mon-goal-level.mjs from
// nethack-c/upstream/dat/Mon-goal.lua. Do not edit by hand.

export const MON_GOAL_LEVEL_MAP = Object.freeze([
    "xxxxxx..xxxxxx...xxxxxxxxx",
    "xxxx......xx......xxxxxxxx",
    "xx.xx.............xxxxxxxx",
    "x....................xxxxx",
    "......................xxxx",
    "......................xxxx",
    "xx........................",
    "xxx......................x",
    "xxx................xxxxxxx",
    "xxxx.....x.xx.......xxxxxx",
    "xxxxx...xxxxxx....xxxxxxxx"
]);
