// Generated by scripts/generate-quest-text.mjs from dat/quest.lua.
// Do not edit by hand.  Rerun the script to update.
//
// C ref: questpgr.c com_pager_core().  Each entry maps a message ID to
// its text, optional output mode, and optional synopsis.  For messages
// with multiple variants (arrays), com_pager_core() picks one at random
// via rn2(nelems).

// eslint-disable-next-line no-unused-vars
export const QUEST_TEXT = {
    "Arc": {
        "firsttime": {
            "text": "You are suddenly in familiar surroundings.  The buildings in the distance\nseem to be those of your old alma mater, but something is wrong.  It feels\nas if there has been a riot recently, or %H has\nbeen under siege.\n\nAll of the windows are boarded up, and there are objects scattered around\nthe entrance.\n\nStrange forbidding shapes seem to be moving in the distance.",
            "output": "text",
            "synopsis": "[You arrive at %H, but all is not well.]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\nYou have an odd feeling this may be the last time you ever come here."
        },
        "locate_first": {
            "text": "A plain opens before you.  Beyond the plain lies a foreboding edifice.\n\nYou have the feeling that you will soon find the entrance to\n%i.",
            "output": "text",
            "synopsis": "[This foreboding edifice must hide the entrance to %i.]"
        },
        "locate_next": {
            "text": "Once again, you are near the entrance to %i."
        },
        "goal_first": {
            "text": "A strange feeling washes over you, and you think back to things you\nlearned during the many lectures of %l.\n\nYou realize the feeling must be the presence of %o.",
            "output": "text",
            "synopsis": "[This strange feeling must be the presence of %o.]"
        },
        "goal_next": {
            "text": "The familiar presence of %o is in the ether."
        },
        "goal_alt": {
            "text": "You have returned to %ns lair."
        },
        "leader_first": {
            "text": "\"Finally you have returned, %p.  You were always\nmy most promising student.  Allow me to see if you are ready for the\nmost difficult task of your career.\"",
            "output": "text",
            "synopsis": "[\"You have returned, %p, to a difficult task.\"]"
        },
        "assignquest": {
            "text": "\"Grave times have befallen the college, for %na has\nstolen %o.  Without it, the board of directors of\nthe university will soon have no choice but to revoke our research grants.\n\n\"You must locate the entrance to %i.  Within it,\nyou will find %n.\n\n\"You must then defeat %n and return %o\nto me.\n\n\"Only in this way will we be able to prevent the budget cuts that could\nclose this college.\n\n\"May the wisdom of %d be your guide.\"",
            "output": "text",
            "synopsis": "[%nC has stolen %o.  Locate %i, defeat %ni, and return %O.]"
        },
        "badalign": {
            "text": "\"%pC!  I've heard that you've been using sloppy techniques.  Your\nresults lately can hardly be called suitable for %ra!\n\n\"How could you have strayed from the %a path?  Go from here, and come\nback only when you have purified yourself.\"",
            "output": "text",
            "synopsis": "[\"%pC, you have strayed from the %a path.  Purify yourself!\"]"
        }
    },
    "Bar": {
        "firsttime": {
            "text": "Warily you scan your surroundings, all of your senses alert for signs\nof possible danger.  Off in the distance, you can %x the familiar shapes\nof %H.\n\nBut why, you think, should %l be there?\n\nSuddenly, the hairs on your neck stand on end as you detect the aura of\nevil magic in the air.\n\nWithout thought, you ready your weapon, and mutter under your breath:\n\n    \"By %d, there will be blood spilt today.\"",
            "output": "text",
            "synopsis": "[You reach the vicinity of %H, but sense evil magic nearby.]"
        },
        "nexttime": {
            "text": "Once again, you near %H.  You know that %l\nwill be waiting."
        },
        "othertime": {
            "text": "Again, and you think possibly for the last time, you approach\n%H."
        },
        "locate_first": {
            "text": "The scent of water comes to you in the desert breeze.  You know that\nyou have located %i.",
            "output": "text",
            "synopsis": "[You have located %i.]"
        },
        "locate_next": {
            "text": "Yet again you have a chance to infiltrate %i."
        },
        "goal_first": {
            "text": "The hairs on the nape of your neck lift as you sense an energy in the\nvery air around you.  You fight down a primordial panic that seeks to\nmake you turn and run.  This is surely the lair of %n.",
            "output": "text",
            "synopsis": "[This is surely the lair of %n.]"
        },
        "goal_next": {
            "text": "Yet again you feel the air around you heavy with malevolent magical energy."
        },
        "leader_first": {
            "text": "\"Ah, %p.  You have returned at last.  The world is in dire\nneed of your help.  There is a great quest you must undertake.\n\n\"But first, I must see if you are ready to take on such a challenge.\"",
            "output": "text",
            "synopsis": "[\"At last you have returned.  There is a great quest you must undertake.\"]"
        },
        "assignquest": {
            "text": "\"The world is in great need of your assistance, %p.\n\n\"About six months ago, I learned that a mysterious sorcerer, known\nas %n, had begun to gather a large group of cutthroats and brigands\nabout %ni.\n\n\"At about the same time, these people you once rode with `liberated' a\npotent magical talisman, %o, from a Turanian caravan.\n\n\"%nC and %nj Black Horde swept down upon %i and defeated\nthe people there, driving them out into the desert.  He has taken\n%o, and seeks to bend it to %nj will.  I detected the\nsubtle changes in the currents of fate, and joined these people.\nThen I sent forth a summons for you.\n\n\"If %n can bend %o to %nj will, he will become\nalmost indestructible.  He will then be able to enslave the minds of\nmen across the world.  You are the only hope.  The gods smile upon you,\nand with %d behind you, you alone can defeat %n.\n\n\"You must go to %i.  From there, you can track down\n%n, defeat %ni, and return %o to us.  Only\nthen will the world be safe.\"",
            "output": "text",
            "synopsis": "[\"Find %n, defeat %ni, and return %o to us.\"]"
        },
        "badalign": {
            "text": "\"%pC!  You have wandered from the path of the %a!\nIf you attempt to overcome %n in this state, he will surely\nenslave your soul.  Your only hope, and ours, lies in your purification.\nGo forth, and return when you feel ready.\"",
            "output": "text",
            "synopsis": "[\"You have wandered from the path of the %a.  Come back when you have atoned.\"]"
        }
    },
    "Cav": {
        "firsttime": {
            "text": "You descend through a barely familiar stairwell that you remember\n%l showing you when you embarked upon your vision quest.\n\nYou arrive back at %H, but something seems\nwrong here.  The usual smoke and glowing light of the fires of the\nouter caves are absent, and an uneasy quiet fills the damp air.",
            "output": "text",
            "synopsis": "[You arrive back at %H, but something is wrong here.]"
        },
        "nexttime": {
            "text": "Once again, you arrive back at %H."
        },
        "othertime": {
            "text": "For some reason, you think that this may be the last time you will\nenter %H."
        },
        "locate_first": {
            "text": "You %x many large claw marks on the ground.  The tunnels ahead\nof you are larger than most of those in any cave complex you have\never been in before.\n\nYour nose detects the smell of carrion from within, and bones litter\nthe sides of the tunnels.",
            "output": "text",
            "synopsis": "[You %x many large claw marks, smell carrion, and notice bones.]"
        },
        "locate_next": {
            "text": "Once again, you approach %i."
        },
        "goal_first": {
            "text": "You find yourself in a large cavern, with neatly polished walls, that\nnevertheless show signs of being scorched by fire.\n\nBones litter the floor, and there are objects scattered everywhere.\nThe air is close with the stench of sulphurous fumes.\n\n%nC is clearly visible, but %nh seems to be asleep.",
            "output": "text",
            "synopsis": "[You enter a large cavern.  %nC is present.]"
        },
        "goal_next": {
            "text": "Once again, you find yourself in the lair of %n."
        },
        "leader_first": {
            "text": "\"You have returned from your vision quest, %p.  Thank %d.\n\n\"We are in dire need of your help, my %S.\n\n\"But first, I must see if you are yet capable of the quest I would\nask you to undertake.\"",
            "output": "text",
            "synopsis": "[\"You have returned.  We are in dire need of your help.\"]"
        },
        "assignquest": {
            "text": "\"You are indeed ready now, %p.  I shall tell you a tale of\ngreat suffering among your people:\n\n\"Shortly after you left on your vision quest, the caves were invaded by\nthe creatures sent against us by %n.\n\n\"She, herself, could not attack us due to her great size, but her minions\nhave harassed us ever since.  In the first attacks, many died, and the\nminions of %n managed to steal %o.\nThey took it to %i and there, none of our\n%g warriors have been able to go.\n\n\"You must find %i, and within it wrest\n%o from %n.  She guards it as\njealously as she guards all treasures she attains.  But with it,\nwe can make our caves safe once more.\n\n\"Please, %p, recover %o for us, and return it here.\"",
            "output": "text",
            "synopsis": "[Find and defeat %n, recover %o, and return with it.]"
        },
        "badalign": {
            "text": "\"%pC!  You have deviated from my teachings.  You no longer follow\nthe path of the %a as you should.  I banish you from these caves, to\ngo forth and purify yourself.  Then, you might be able to accomplish this\nquest.\"",
            "output": "text",
            "synopsis": "[\"You no longer follow the path of the %a.  Go, and purify yourself.\"]"
        }
    },
    "Hea": {
        "firsttime": {
            "text": "What sorcery has brought you back to %H?  The smell\nof fresh funeral pyres tells you that something is amiss with the healing\npowers that used to practice here.\n\nNo rhizotomists are tending the materia medica gardens, and where are the\ncommon folk who used to come for the cures?\n\nYou know that you must quickly make your way to the collegium, and\n%ls iatreion, and find out what has happened in your absence.",
            "output": "text",
            "synopsis": "[You arrive back at %H and must find %l.]"
        },
        "nexttime": {
            "text": "After your last experience you expected to be here, but you certainly\ndid not expect to see things so much worse.  This time you must succeed."
        },
        "othertime": {
            "text": "Again, you %x %H in the distance.\n\nThe smell of death and disease permeates the air.  You do not have\nto be %Ra to know that %n is on the verge of victory."
        },
        "locate_first": {
            "text": "You stand before the entrance to %i.  Strange\nscratching noises come from within the building.\n\nThe swampy ground around you seems to stink with disease.",
            "output": "text",
            "synopsis": "[You have reached %i but all is not well.]"
        },
        "locate_next": {
            "text": "Once again you stand at the entrance to %i."
        },
        "goal_first": {
            "text": "You stand within sight of the infamous Isle of %n.  Even\nthe words of %l had not prepared you for this.\n\nSteeling yourself against the wails of the ill that pierce your ears,\nyou hurry on your task.  Maybe with %o you can\nheal them on your return, but not now.",
            "output": "text",
            "synopsis": "[You have reached the lair of %n.  Take %o away from %ni.]"
        },
        "goal_next": {
            "text": "Once again, you %x the Isle of %n in the distance."
        },
        "leader_first": {
            "text": "Feebly, %l raises %lj head to look at you.\n\n\"It is good to see you again, %p.  I see the concern in your\neyes, but do not worry for me.  I am not ready for Hades yet.  We have\nexhausted much of our healing powers holding off %n.\nI need your fresh strength to carry on our work.\n\n\"Come closer and let me lay hands on you, and determine if you have\nthe skills necessary to accomplish this mission.\"",
            "output": "text",
            "synopsis": "[%l is weak from the struggle with %n.  %lH wants to examine you.]"
        },
        "assignquest": {
            "text": "For the first time, you sense a smile on %ls face.\n\n    \"You have indeed learned as much as we can teach you in preparation\n    for this task.  Let me tell you what I know of the symptoms and hope\n    that you can provide a cure.\n\n    \"A short while ago, the dreaded %nt was fooled by the gods\n    into thinking that %nh could use %o to find a\n    cure for old age.  Think of it, eternal youth!  But %nj good\n    health is accomplished by drawing the health from those around %ni.\n\n    \"He has exhausted %nj own supply of healthy people and now %nh seeks to\n    extend %nj influence into our world.  You must recover from %ni\n    %o and break the spell.\n\n    \"You must travel into the swamps to %i, and from there\n    follow the trail to %ns island lair.  Be careful.\"",
            "output": "text",
            "synopsis": "[Travel to %i on your way to recover %o from %n.]"
        },
        "badalign": {
            "text": "\"You have learned much of the remedies that benefit, but you must also\nknow which physic for which ail.  That is why %ds teachings are a\npart of your training.\n\n\"Return to us when you have healed thyself.\"",
            "output": "text",
            "synopsis": "[Return when you are more %a.]"
        }
    },
    "Kni": {
        "firsttime": {
            "text": "You materialize in the shadows of %H.  Immediately, you notice\nthat something is wrong.  The fields around the castle are trampled and\nwithered, as if some great battle has been recently fought.\n\nExploring further, you %x long gouges in the walls of %H.\nYou know of only one creature that makes those kinds of marks...",
            "output": "text",
            "synopsis": "[Signs of battle include long gouges in the walls of %H.]"
        },
        "nexttime": {
            "text": "Once again you stand in the shadows of %H."
        },
        "othertime": {
            "text": "Again, you stand before %H.  You vaguely sense that this\nmay be the last time you stand before %l."
        },
        "locate_first": {
            "text": "You stand at the foot of %i.  Atop, you can %x a shrine.\nStrange energies seem to be focused here, and the hair on the back of\nyour neck stands on end.",
            "output": "text",
            "synopsis": "[You have reached %i and can %x a shrine.]"
        },
        "locate_next": {
            "text": "Again, you stand at the foot of %i."
        },
        "goal_first": {
            "text": "As you exit the swamps, you %x before you a huge, gaping hole in the\nside of a hill.  From within, you smell the foul stench of carrion.\n\nThe pools on either side of the entrance are fouled with blood, and\npieces of rusted metal and broken weapons show above the surface.",
            "output": "text",
            "synopsis": "[You %x the entrance to a cavern inside a hill.]"
        },
        "goal_next": {
            "text": "Again, you stand at the entrance to %ns lair."
        },
        "leader_first": {
            "text": "\"Ah, %p.  We see thou hast received Our summons.\nWe are in dire need of thy prowess.  But first, We must needs\ndecide if thou art ready for this great undertaking.\"",
            "output": "text",
            "synopsis": "[%lC checks whether you are ready for a great undertaking.]"
        },
        "assignquest": {
            "text": "\"Ah, %p.  Thou art truly ready, as no %c before thee hath\nbeen.  Hear now Our words:\n\n\"As thou noticed as thou approached %H, a great battle hath\nbeen fought recently in these fields.  Know thou that Merlin himself\ncame to aid Us here as We battled the foul %n.  In the midst of that\nbattle, %n struck Merlin a great blow, felling him.  Then, as Our\nforces were pressed back, %n stole %o.\n\n\"We eventually turned the tide, but lost many %cP in doing so.\nMerlin was taken off by his apprentice, but hath not recovered.  We have\nbeen told that so long as %n possesseth %o,\nMerlin will not regain his health.\n\n\"We hereby charge thee with this most important of duties:\n\n\"Go forth from this place, to the fens, and there thou wilt find\n%i.  From there, thou must track down %n.  Destroy the\nbeast, and return to Us %o.  Only then can\nWe restore Merlin to health.\"",
            "output": "text",
            "synopsis": "[Pass through %i to reach %n.  Destroy %ni and return with %o.]"
        },
        "badalign": {
            "text": "\"Thou dishonourest Us, %p!  Thou hast strayed from the path of\nchivalry! Go from Our presence and do penance.  Only when thou art again\npure mayst thou return hence.\"",
            "output": "text",
            "synopsis": "[Go and do penance.  Return when you are truly %a.]"
        }
    },
    "Mon": {
        "firsttime": {
            "text": "You find yourself standing in sight of %H.\nSomething is obviously wrong here.  Strange shapes lumber around\noutside %H!\n\nYou realize that %l needs your assistance!",
            "output": "text",
            "synopsis": "[You have reached %H but something is wrong.  %lC needs your aid.]"
        },
        "nexttime": {
            "text": "Once again, you stand before %H."
        },
        "othertime": {
            "text": "Again you face %H.  Your intuition hints that this\nmay be the final time you come here."
        },
        "locate_first": {
            "text": "You remember the descriptions of %i, given\nto you by %l.  It is ahead that you will find\n%n's trail.",
            "output": "text",
            "synopsis": "[You have reached %i.  %nC lurks further ahead.]"
        },
        "locate_next": {
            "text": "Again, you stand before %i."
        },
        "goal_first": {
            "text": "The stench of brimstone is all about you, and the elementals close in\nfrom all sides!\n\nAhead, there is a small clearing amidst the bubbling pits of lava...",
            "output": "text",
            "synopsis": "[You are surrounded by brimstone, lava, and elementals.]"
        },
        "goal_next": {
            "text": "Again, you have invaded %ns domain."
        },
        "leader_first": {
            "text": "\"Ah, %p, my %S.  You have returned to us at last.\nA great blow has befallen our order; perhaps you can help us.\nFirst, however, I must determine if you are prepared for this\ngreat challenge.\"",
            "output": "text",
            "synopsis": "[%lC checks whether you are ready for the great challenge.]"
        },
        "assignquest": {
            "text": "\"Yes, %p.  You are truly ready now.  Attend to me and I shall\ntell you of what has transpired:\n\n\"During one of the Great Meditations a short time ago, %n and\na legion of elementals invaded %H.  Many %gP\nwere killed, including the one bearing %o.\n\nNow, there are barely enough %gP left to keep the elementals\nat bay.\n\n\"We need you to find %i, then, from there,\ntravel to %ns lair.  If you can manage to defeat %n and\nreturn %o here, we can then drive off the legions\nof elementals that slay our students.\n\n\"Go with %d as your guide, %p.\"",
            "output": "text",
            "synopsis": "[Find %i, then continue to %ns lair.  Defeat %ni and return with %o.]"
        },
        "badalign": {
            "text": "\"This is terrible, %p.  You have deviated from the true path!\nYou know that %d requires the most strident devotion of this\norder.  The %shood must stand for utmost piety.\n\n\"Go from here, atone for your sins against %d.  Return only when\nyou have purified yourself.\"",
            "output": "text",
            "synopsis": "[You must atone.  Come back when you are worthy of %d.]"
        }
    },
    "Pri": {
        "firsttime": {
            "text": "You find yourself standing in sight of %H.  Something\nis obviously wrong here.  The doors to %H, which usually\nstand open, are closed.  Strange human shapes shamble around\noutside.\n\nYou realize that %l needs your assistance!",
            "output": "text",
            "synopsis": "[You are at %H; the doors are closed.  %lC needs your help!]"
        },
        "nexttime": {
            "text": "Once again, you stand before %H."
        },
        "othertime": {
            "text": "Again you face %H.  Your intuition hints that this may be\nthe final time you come here."
        },
        "locate_first": {
            "text": "You stand facing a large graveyard.  The sky above is filled with clouds\nthat seem to get thicker closer to the center.  You sense the presence of\nundead in larger numbers than you have ever encountered before.\n\nYou remember the descriptions of %i, given to you by\n%l.  It is ahead that you will find %ns trail.",
            "output": "text",
            "synopsis": "[You have found %i.  The trail to %n lies ahead.]"
        },
        "locate_next": {
            "text": "Again, you stand before %i."
        },
        "goal_first": {
            "text": "The stench of brimstone is all about you, and the shrieks and moans\nof tortured souls assault your psyche.\n\nAhead, there is a small clearing amidst the bubbling pits of lava...",
            "output": "text",
            "synopsis": "[The stench of brimstone surrounds you, the shrieks and moans are endless.]"
        },
        "goal_next": {
            "text": "Again, you have invaded %ns domain."
        },
        "leader_first": {
            "text": "\"Ah, %p, my %S.  You have returned to us at last.\nA great blow has befallen our order; perhaps you can help us.\nFirst, however, I must determine if you are prepared for this\ngreat challenge.\"",
            "output": "text",
            "synopsis": "[You have returned and we need your help.  Are you ready?]"
        },
        "assignquest": {
            "text": "\"Yes, %p.  You are truly ready now.  Attend to me and I shall\ntell you of what has transpired:\n\n\"At one of the Great Festivals a short time ago, %n and a legion\nof undead invaded %H.  Many %gP were killed, including\nthe one carrying %o.\n\n\"As a final act of vengefulness, %n desecrated the altar here.\nWithout it, we could not mount a counter-attack.  Now, there are\nbarely enough %gP left to keep the undead at bay.\n\n\"We need you to find %i, then, from there, travel\nto %ns lair.  If you can manage to defeat %n and return\n%o here, we can then drive off the legions of\nundead that befoul the land.\n\n\"Go with %d as your guide, %p.\"",
            "output": "text",
            "synopsis": "[%nC invaded %H and captured %o.  Defeat %ni and retrieve %oh.]"
        },
        "badalign": {
            "text": "\"This is terrible, %p.  You have deviated from the true path!\nYou know that %d requires the most strident devotion of this\norder.  The %shood must stand for utmost piety.\n\n\"Go from here, atone for your sins against %d.  Return only when\nyou have purified yourself.\"",
            "output": "text",
            "synopsis": "[You have deviated from the path.  Return when you have purified yourself.]"
        }
    },
    "Ran": {
        "firsttime": {
            "text": "You arrive in familiar surroundings.  In the distance, you %x the\nancient forest grove, the place of worship to %d.\n\nSomething is wrong, though.  Surrounding the grove are centaurs!\nAnd they've noticed you!",
            "output": "text",
            "synopsis": "[The ancient forest grove is surrounded by centaurs.]"
        },
        "nexttime": {
            "text": "Once again, you stand before %H."
        },
        "othertime": {
            "text": "You have the oddest feeling that this may be the last time you\nare to enter %H."
        },
        "locate_first": {
            "text": "This must be %i.\n\nYou are in a cave built of many different rooms, all interconnected\nby tunnels.  Your quest is to find and shoot the evil wumpus that\nresides elsewhere in the cave without running into any bottomless\npits or using up your limited supply of arrows.  Good luck.\n\nYou are in room 9 of the cave.  There are tunnels to rooms\n5, 8, and 10.\n*rustle* *rustle* (must be bats nearby.)\n*sniff* (I can smell the evil wumpus nearby!)",
            "output": "text",
            "synopsis": "[This is %i.  There are bats nearby.  Beware the wumpus!]"
        },
        "locate_next": {
            "text": "Once again, you descend into %i.\n\n*whoosh* (I feel a draft from some pits.)\n*rustle* *rustle* (must be bats nearby.)",
            "output": "text",
            "synopsis": "[You are in %i.  There are pits.  There are bats nearby.]"
        },
        "goal_first": {
            "text": "You descend into a weird place, in which roughly cut cave-like walls\njoin with smooth, finished ones, as if someone was in the midst of\nfinishing off the construction of a subterranean complex.\n\nOff in the distance, you hear a sound like the clattering of many\nhooves on rock.",
            "output": "text",
            "synopsis": "[You descend into a subterranean complex.  Hooves clatter in the distance.]"
        },
        "goal_next": {
            "text": "Once again, you enter the distorted castle of %n."
        },
        "leader_first": {
            "text": "\"%pC!  You have returned!  Thank %d.\n\n\"We have great need of you.  But first, I must see if you have the\nrequired abilities to take on this responsibility.\"",
            "output": "text",
            "synopsis": "[You have returned, %p.  We need your help.  Are you ready?]"
        },
        "assignquest": {
            "text": "\"You are indeed ready, %p.  I shall tell you what has transpired,\nand why we so desperately need your help:\n\n\"A short time ago, the mountain centaurs to the east invaded\nand enslaved the plains centaurs in this area.  The local\nleader is now only a figurehead, and serves %n.\n\n\"During our last gathering of worship here, we were beset by hordes of\nhostile centaurs, as you witnessed.  In the first onslaught a group,\nheaded by %n %niself, managed to breach the grove and steal\n%o.\n\n\"Since then, we have been besieged.  We do not know how much longer\nwe will be able to maintain our magical barriers.\n\n\"If we are to survive, you, %p, must infiltrate\n%i.  There, you will find a pathway down, to the\nunderground cavern of %n.  He has always coveted\n%o, and will surely keep it.\n\n\"Recover %o for us, %p!  Only then will %d be safe.\"",
            "output": "text",
            "synopsis": "[%nC has stolen %o.  Infiltrate %i and retrieve %oh for us.]"
        },
        "badalign": {
            "text": "\"You have strayed, %p!  You know that %d requires that\nwe maintain a pure devotion to things %a!\n\n\"You must go from us.  Return when you have purified yourself.\"",
            "output": "text",
            "synopsis": "[You are not sufficiently %a.  Come back when you have purified yourself.]"
        }
    },
    "Rog": {
        "firsttime": {
            "text": "Unexpectedly, you find yourself back in Ransmannsby, where you trained to\nbe a thief.  Quickly you make the guild sign, hoping that you AND word\nof your arrival reach %ls den.",
            "output": "text",
            "synopsis": "[You are in Ransmannsby, where you trained.  Find %l.]"
        },
        "nexttime": {
            "text": "Once again, you find yourself back in Ransmannsby.  Fond memories are\nreplaced by fear, knowing that %l is waiting for you."
        },
        "othertime": {
            "text": "You rub your hands through your hair, hoping that the little ones on\nthe back of your neck stay down, and prepare yourself for your meeting\nwith %l."
        },
        "locate_first": {
            "text": "Those damn little hairs tell you that you are nearer to %o."
        },
        "locate_next": {
            "text": "Not wanting to face %l without having stolen %o, you continue."
        },
        "goal_first": {
            "text": "You feel a great swelling up of courage, sensing the presence of\n%o.  Or is it fear?",
            "output": "text",
            "synopsis": "[You sense %o.]"
        },
        "goal_next": {
            "text": "The hairs on the back of your neck whisper -- it's fear."
        },
        "leader_first": {
            "text": "\"Well, look who it is boys -- %p has come home.  You seem to have\nfallen behind in your dues.  I should kill you as an example to these\nother worthless cutpurses, but I have a better plan.  If you are ready\nmaybe you could work off your back dues by performing a little job for\nme.  Let us just see if you are ready...\"",
            "output": "text",
            "synopsis": "[You owe back dues to your guild.  You can pay them off if you're up to the job.]"
        },
        "assignquest": {
            "text": "\"Will everyone not going to retrieve %o from that\njerk, %n, take one step backwards.  Good choice,\n%p, because I was going to send you anyway.  My other %gp\nare too valuable to me.\n\n\"Here's the deal.  I want %o, %n\nhas %o.  You are going to get %o\nand bring it back to me.  So simple an assignment even you can understand\nit.\"",
            "output": "text",
            "synopsis": "[Get %o from %n and bring it to %l.]"
        },
        "badalign": {
            "text": "\"Maybe I should chain you to my perch here for a while.  Perhaps watching\nreal %a men at work will bring some sense back to you.  I don't\nthink I could stand the sight of you for that long though.  Come back\nwhen you can be trusted to act properly.\"",
            "output": "text",
            "synopsis": "[Come back when you are really %a.]"
        }
    },
    "Sam": {
        "firsttime": {
            "text": "Even before your senses adjust, you recognize the kami of\n%H.\n\nYou %x the standard of your teki, %n, flying above\nthe town.  How could such a thing have happened?  Why are ninja\nwandering freely; where are the samurai of your daimyo, %l?\n\nYou quickly say a prayer to Izanagi and Izanami and walk towards\ntown.",
            "output": "text",
            "synopsis": "[The banner of %n flies above town.  What has happened to %l?]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\n\nInstantly you sense a subtle change in your karma.  You seem to know that\nif you do not succeed in your quest, %n will have destroyed\nthe kami of %H before you return again.",
            "output": "text",
            "synopsis": "[%HC is threatened by %n.]"
        },
        "locate_first": {
            "text": "You instinctively reach for your swords.  You do not recognize the\nlay of this land, but you know that your teki are everywhere."
        },
        "locate_next": {
            "text": "Thankful that your %sp at %H cannot see\nyour fear, you prepare again to advance."
        },
        "goal_first": {
            "text": "In your mind, you hear the taunts of %n.\n\nYou become like the rice plant and bend to the ground, offering a\nprayer to %d.  But when the wind has passed, you stand\nproudly again.  Putting your kami in the hands of fate, you advance.",
            "output": "text",
            "synopsis": "[You feel the taunts %n, but after offering a prayer to %d, you proceed.]"
        },
        "goal_next": {
            "text": "As you arrive once again at the home of %n, your thoughts\nturn only to %o."
        },
        "goal_alt": {
            "text": "As you arrive once again at the home of %n."
        },
        "leader_first": {
            "text": "\"Ah, %p-san, it is good to see you again.  I need someone who can\nlead my samurai against %n.  If you are ready, you will be\nthat person.\"",
            "output": "text",
            "synopsis": "[%lC needs someone to lead %lj samurai against %n.  Are you ready?]"
        },
        "assignquest": {
            "text": "\"Domo %p-san, indeed you are ready.  I can now tell you what\nit is that I require of you.\n\n\"The daimyo, %n, has betrayed us.  He has stolen from us\n%o and taken it to his donjon deep within\n%i.\n\n\"If I cannot show the emperor %o when he comes\nfor the festival he will know that I have failed in my duty, and\nrequest that I commit seppuku.\n\n\"You must gain entrance to %i and retrieve the\nemperor's property.  Be quick!  The emperor will be here for the\ncha-no-you in 5 sticks.\n\n\"Wakarimasu ka?\"",
            "output": "text",
            "synopsis": "[You must enter %i, then regain %o from %n.]"
        },
        "badalign": {
            "text": "\"%p-san, you would do better to join the kyokaku.\n\n\"You have skills, but until you can call upon the bushido to know when and\nhow to use them you are not samurai.  When you can think %a and\nact %a then return.\"",
            "output": "text",
            "synopsis": "[When you can think %a and act %a then return.]"
        }
    },
    "Tou": {
        "firsttime": {
            "text": "You breathe a sigh of relief as you find yourself back in the familiar\nsurroundings of %H.\n\nYou quickly notice that things do not appear the way they did when you\nleft.  The town is dark and quiet.  There are no sounds coming from\nbehind the town walls, and no campfires burning in the fields.  As a\nmatter of fact, you do not %x any movement in the fields at all, and\nthe crops seem as though they have been untended for many weeks.",
            "output": "text",
            "synopsis": "[You find yourself back at %H, but the quiet is ominous.]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\nThings appear to have become so bad that you fear that soon\n%H will not be here to return to."
        },
        "locate_first": {
            "text": "Only your faith in %d keeps you from trembling.  You %x\nthe handiwork of %ns henchlings everywhere.",
            "output": "text",
            "synopsis": "[You %x the handiwork of %ns henchlings.]"
        },
        "locate_next": {
            "text": "You know that this time you must find and destroy %n."
        },
        "goal_first": {
            "text": "You sense the presence of %o."
        },
        "goal_next": {
            "text": "You gain confidence, knowing that you may soon be united with\n%o."
        },
        "goal_alt": {
            "text": "You have returned to %ns lair."
        },
        "leader_first": {
            "text": "\"Is it really you, %p!  I had given up hope for your return.\nAs you can %x, we are desperately in need of your talents.  Someone must\ndefeat %n if our town is to become what it once was.\n\n\"Let me see if you are ready to be that someone.\"",
            "output": "text",
            "synopsis": "[Someone must defeat %n.  Are your ready?]"
        },
        "assignquest": {
            "text": "\"You have indeed proven yourself a worthy %c, %p.\n\n\"But now your kinfolk and I must ask you to put aside your travels and\nhelp us in our time of need.  After you left us we elected a new mayor,\n%n.  He proved to be a most heinous and vile creature.\n\n\"Soon after taking office he absconded with %o\nand fled town, leaving behind his henchmen to rule over us.  In order\nfor us to regain control of our town, you must enter %i\nand recover %o.\n\n\"Do not be distracted on your quest.  If you do not return quickly I fear\nthat all will be lost.  Let us both pray now that %d will guide you\nand keep you safe.\"",
            "output": "text",
            "synopsis": "[Enter %i and recover %o from %n.]"
        },
        "badalign": {
            "text": "\"It would be an affront to %d to have one not true to the\n%a path undertake her bidding.\n\n\"You must not return to us until you have purified yourself of these\nbad influences on your actions.  Remember, only by following the %a\npath can you hope to overcome the obstacles you will face.\"",
            "output": "text",
            "synopsis": "[You are not sufficiently %a.  Return when you are.]"
        }
    },
    "Val": {
        "firsttime": {
            "text": "You materialize at the base of a snowy hill.  Atop the hill sits\na place you know well, %H.  You immediately realize\nthat something here is very wrong!\n\nIn places, the snow and ice have been melted into steaming pools of\nwater.  Fumaroles and pools of bubbling lava surround the hill.\nThe stench of sulphur is carried through the air, and you %x creatures\nthat should not be able to live in this environment moving towards you.",
            "output": "text",
            "synopsis": "[You arrive below %H.  Something is wrong; there is lava present.]"
        },
        "nexttime": {
            "text": "Once again, you are near the abode of %l."
        },
        "othertime": {
            "text": "Again you materialize near %ls abode.  You have a nagging feeling\nthat this may be the last time you come here."
        },
        "locate_first": {
            "text": "The ice and snow gives way to a valley floor.  You %x ahead of you\na huge round hill surrounded by pools of lava.  This then is the entrance\nto %i.  It looks like you're not going to get in without\na fight though.",
            "output": "text",
            "synopsis": "[This is the entrance to %i.]"
        },
        "locate_next": {
            "text": "Once again, you stand before the entrance to %i."
        },
        "goal_first": {
            "text": "Through clouds of sulphurous gasses, you %x a rock palisade\nsurrounded with a moat of bubbling lava.  You remember the description\nfrom something that %l said.  This is the lair of %n.",
            "output": "text",
            "synopsis": "[This is the lair of %n.]"
        },
        "goal_next": {
            "text": "Once again, you stand in sight of %ns lair."
        },
        "leader_first": {
            "text": "\"Ah, %p, my %S.  You have returned to %H\nat last.  We are in dire need of your aid, but I must determine if you\nare yet ready for such an undertaking.\n\n\"Let me read your fate...\"",
            "output": "text",
            "synopsis": "[We need your aid.  Are you ready?]"
        },
        "assignquest": {
            "text": "\"It is not clear, %p, for my sight is limited without our relic.\nBut it is now likely that you can defeat %n, and recover\n%o.\n\n\"A short time ago, %n and his minions attacked this place.  They\nopened the huge volcanic vents you %x about the hill, and attacked.  I knew\nthat this was to come to pass, and had asked %d for a group of %gP\nto help defend this place.  The few you %x here are the mightiest of\nValhalla's own, and are all that are left of one hundred %d sent.\n\n\"Despite the great and glorious battle we fought, %n managed at\nlast to steal %o.  This has upset the balance of the universe,\nand unless %oh is returned into my care, %n may start Ragnarok.\n\n\"You must find the entrance to %i.  Travel downward\nfrom there and you will find %ns lair.  Defeat him and\nreturn %o to me.\"",
            "output": "text",
            "synopsis": "[Find %i; defeat %n; return with %o.]"
        },
        "badalign": {
            "text": "\"NO!  This is terrible.  I see you becoming an ally of %n, and\nleading his armies in the final great battles.  This must not come to\npass!  You have strayed from the %a path.  You must purge yourself,\nand return here only when you have regained a state of purity.\"",
            "output": "text",
            "synopsis": "[You have strayed from the %a path.  Return after you purify yourself.]"
        }
    },
    "Wiz": {
        "firsttime": {
            "text": "You are suddenly in familiar surroundings.  You notice what appears to\nbe a large, squat stone structure nearby.  Wait!  That looks like the\ntower of your former teacher, %l.\n\nHowever, things are not the same as when you were last here.  Mists and\nareas of unexplained darkness surround the tower.  There is movement in\nthe shadows.\n\nYour teacher would never allow such unaesthetic forms to surround the\ntower...  unless something were dreadfully wrong!",
            "output": "text",
            "synopsis": "[You have arrived at %ls tower but something is very wrong.]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\nYou have an odd feeling this may be the last time you ever come here."
        },
        "locate_first": {
            "text": "Wisps of fog swirl nearby.  You feel that %ns lair is close."
        },
        "locate_next": {
            "text": "You believe that you may once again invade %i."
        },
        "goal_first": {
            "text": "You feel your mentor's presence; perhaps %o is nearby."
        },
        "goal_next": {
            "text": "The aura of %o tingles at the edge of your perception."
        },
        "goal_alt": {
            "text": "You have returned to %ns lair."
        },
        "leader_first": {
            "text": "\"Come closer, %p, for my voice falters in my old age.\nYes, I see that you have come a long way since you went out into the\nworld, leaving the safe confines of this tower.  However, I must first\ndetermine if you have all of the skills required to take on the task\nI require of you.\"",
            "output": "text",
            "synopsis": "[You have come a long way, but are you ready for the task I require?]"
        },
        "assignquest": {
            "text": "\"Yes, %p, you truly are ready for this dire task.  Listen,\ncarefully, for what I tell you now will be of vital importance.\n\n\"Since you left us to hone your skills in the world, we unexpectedly came\nunder attack by the forces of %n.  As you know, we thought\n%n had perished at the end of the last age, but, alas, this was\nnot the case.\n\n\"%nC sent an army of abominations against us.  Among them was a\nminion, mindless and ensorcelled, and thus, in the confusion, it was\nable to penetrate our defenses.  Alas, this creature has stolen\n%o and I fear has delivered %oh to %n.\n\n\"Over the years, I had woven most of my power into this amulet, and thus,\nwithout it, I have but a shadow of my former power, and I fear that I\nshall soon perish.\n\n\"You must travel to %i, and within its dungeons,\nfind and overcome %n, and return %o to me.\n\n\"Go now, with %d, and complete this quest before it is too late.\"",
            "output": "text",
            "synopsis": "[Travel to %i; overcome %n; return with %o.]"
        },
        "badalign": {
            "text": "\"You amaze me, %p!  How many times did I tell you that the way of a mage\nis an exacting one.  One must use the world with care, lest one leave it\nin ruins and simplify the task of %n.\n\n\"You must go back and show your worthiness.  Do not return until you are\ntruly ready for this quest.  May %d guide you in this task.\"",
            "output": "text",
            "synopsis": "[Go; come back when you are worthy of %d.]"
        }
    },
    "_fallbacks": {
        "goal_alt": "goal_next"
    }
};

export const QUEST_TEXT_FALLBACKS = {
    "goal_alt": "goal_next"
};
