// Generated by scripts/generate-quest-text.mjs from dat/quest.lua.
// Do not edit by hand.  Rerun the script to update.
//
// C ref: questpgr.c com_pager_core().  Each entry maps a message ID to
// its text, optional output mode, and optional synopsis.  For messages
// with multiple variants (arrays), com_pager_core() picks one at random
// via rn2(nelems).

 
export const QUEST_TEXT = {
    "Arc": {
        "firsttime": {
            "text": "You are suddenly in familiar surroundings.  The buildings in the distance\nseem to be those of your old alma mater, but something is wrong.  It feels\nas if there has been a riot recently, or %H has\nbeen under siege.\n\nAll of the windows are boarded up, and there are objects scattered around\nthe entrance.\n\nStrange forbidding shapes seem to be moving in the distance.",
            "output": "text",
            "synopsis": "[You arrive at %H, but all is not well.]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\nYou have an odd feeling this may be the last time you ever come here."
        },
        "locate_first": {
            "text": "A plain opens before you.  Beyond the plain lies a foreboding edifice.\n\nYou have the feeling that you will soon find the entrance to\n%i.",
            "output": "text",
            "synopsis": "[This foreboding edifice must hide the entrance to %i.]"
        },
        "locate_next": {
            "text": "Once again, you are near the entrance to %i."
        },
        "goal_first": {
            "text": "A strange feeling washes over you, and you think back to things you\nlearned during the many lectures of %l.\n\nYou realize the feeling must be the presence of %o.",
            "output": "text",
            "synopsis": "[This strange feeling must be the presence of %o.]"
        },
        "goal_next": {
            "text": "The familiar presence of %o is in the ether."
        },
        "goal_alt": {
            "text": "You have returned to %ns lair."
        }
    },
    "Bar": {
        "firsttime": {
            "text": "Warily you scan your surroundings, all of your senses alert for signs\nof possible danger.  Off in the distance, you can %x the familiar shapes\nof %H.\n\nBut why, you think, should %l be there?\n\nSuddenly, the hairs on your neck stand on end as you detect the aura of\nevil magic in the air.\n\nWithout thought, you ready your weapon, and mutter under your breath:\n\n    \"By %d, there will be blood spilt today.\"",
            "output": "text",
            "synopsis": "[You reach the vicinity of %H, but sense evil magic nearby.]"
        },
        "nexttime": {
            "text": "Once again, you near %H.  You know that %l\nwill be waiting."
        },
        "othertime": {
            "text": "Again, and you think possibly for the last time, you approach\n%H."
        },
        "locate_first": {
            "text": "The scent of water comes to you in the desert breeze.  You know that\nyou have located %i.",
            "output": "text",
            "synopsis": "[You have located %i.]"
        },
        "locate_next": {
            "text": "Yet again you have a chance to infiltrate %i."
        },
        "goal_first": {
            "text": "The hairs on the nape of your neck lift as you sense an energy in the\nvery air around you.  You fight down a primordial panic that seeks to\nmake you turn and run.  This is surely the lair of %n.",
            "output": "text",
            "synopsis": "[This is surely the lair of %n.]"
        },
        "goal_next": {
            "text": "Yet again you feel the air around you heavy with malevolent magical energy."
        }
    },
    "Cav": {
        "firsttime": {
            "text": "You descend through a barely familiar stairwell that you remember\n%l showing you when you embarked upon your vision quest.\n\nYou arrive back at %H, but something seems\nwrong here.  The usual smoke and glowing light of the fires of the\nouter caves are absent, and an uneasy quiet fills the damp air.",
            "output": "text",
            "synopsis": "[You arrive back at %H, but something is wrong here.]"
        },
        "nexttime": {
            "text": "Once again, you arrive back at %H."
        },
        "othertime": {
            "text": "For some reason, you think that this may be the last time you will\nenter %H."
        },
        "locate_first": {
            "text": "You %x many large claw marks on the ground.  The tunnels ahead\nof you are larger than most of those in any cave complex you have\never been in before.\n\nYour nose detects the smell of carrion from within, and bones litter\nthe sides of the tunnels.",
            "output": "text",
            "synopsis": "[You %x many large claw marks, smell carrion, and notice bones.]"
        },
        "locate_next": {
            "text": "Once again, you approach %i."
        },
        "goal_first": {
            "text": "You find yourself in a large cavern, with neatly polished walls, that\nnevertheless show signs of being scorched by fire.\n\nBones litter the floor, and there are objects scattered everywhere.\nThe air is close with the stench of sulphurous fumes.\n\n%nC is clearly visible, but %nh seems to be asleep.",
            "output": "text",
            "synopsis": "[You enter a large cavern.  %nC is present.]"
        },
        "goal_next": {
            "text": "Once again, you find yourself in the lair of %n."
        }
    },
    "Hea": {
        "firsttime": {
            "text": "What sorcery has brought you back to %H?  The smell\nof fresh funeral pyres tells you that something is amiss with the healing\npowers that used to practice here.\n\nNo rhizotomists are tending the materia medica gardens, and where are the\ncommon folk who used to come for the cures?\n\nYou know that you must quickly make your way to the collegium, and\n%ls iatreion, and find out what has happened in your absence.",
            "output": "text",
            "synopsis": "[You arrive back at %H and must find %l.]"
        },
        "nexttime": {
            "text": "After your last experience you expected to be here, but you certainly\ndid not expect to see things so much worse.  This time you must succeed."
        },
        "othertime": {
            "text": "Again, you %x %H in the distance.\n\nThe smell of death and disease permeates the air.  You do not have\nto be %Ra to know that %n is on the verge of victory."
        },
        "locate_first": {
            "text": "You stand before the entrance to %i.  Strange\nscratching noises come from within the building.\n\nThe swampy ground around you seems to stink with disease.",
            "output": "text",
            "synopsis": "[You have reached %i but all is not well.]"
        },
        "locate_next": {
            "text": "Once again you stand at the entrance to %i."
        },
        "goal_first": {
            "text": "You stand within sight of the infamous Isle of %n.  Even\nthe words of %l had not prepared you for this.\n\nSteeling yourself against the wails of the ill that pierce your ears,\nyou hurry on your task.  Maybe with %o you can\nheal them on your return, but not now.",
            "output": "text",
            "synopsis": "[You have reached the lair of %n.  Take %o away from %ni.]"
        },
        "goal_next": {
            "text": "Once again, you %x the Isle of %n in the distance."
        }
    },
    "Kni": {
        "firsttime": {
            "text": "You materialize in the shadows of %H.  Immediately, you notice\nthat something is wrong.  The fields around the castle are trampled and\nwithered, as if some great battle has been recently fought.\n\nExploring further, you %x long gouges in the walls of %H.\nYou know of only one creature that makes those kinds of marks...",
            "output": "text",
            "synopsis": "[Signs of battle include long gouges in the walls of %H.]"
        },
        "nexttime": {
            "text": "Once again you stand in the shadows of %H."
        },
        "othertime": {
            "text": "Again, you stand before %H.  You vaguely sense that this\nmay be the last time you stand before %l."
        },
        "locate_first": {
            "text": "You stand at the foot of %i.  Atop, you can %x a shrine.\nStrange energies seem to be focused here, and the hair on the back of\nyour neck stands on end.",
            "output": "text",
            "synopsis": "[You have reached %i and can %x a shrine.]"
        },
        "locate_next": {
            "text": "Again, you stand at the foot of %i."
        },
        "goal_first": {
            "text": "As you exit the swamps, you %x before you a huge, gaping hole in the\nside of a hill.  From within, you smell the foul stench of carrion.\n\nThe pools on either side of the entrance are fouled with blood, and\npieces of rusted metal and broken weapons show above the surface.",
            "output": "text",
            "synopsis": "[You %x the entrance to a cavern inside a hill.]"
        },
        "goal_next": {
            "text": "Again, you stand at the entrance to %ns lair."
        }
    },
    "Mon": {
        "firsttime": {
            "text": "You find yourself standing in sight of %H.\nSomething is obviously wrong here.  Strange shapes lumber around\noutside %H!\n\nYou realize that %l needs your assistance!",
            "output": "text",
            "synopsis": "[You have reached %H but something is wrong.  %lC needs your aid.]"
        },
        "nexttime": {
            "text": "Once again, you stand before %H."
        },
        "othertime": {
            "text": "Again you face %H.  Your intuition hints that this\nmay be the final time you come here."
        },
        "locate_first": {
            "text": "You remember the descriptions of %i, given\nto you by %l.  It is ahead that you will find\n%n's trail.",
            "output": "text",
            "synopsis": "[You have reached %i.  %nC lurks further ahead.]"
        },
        "locate_next": {
            "text": "Again, you stand before %i."
        },
        "goal_first": {
            "text": "The stench of brimstone is all about you, and the elementals close in\nfrom all sides!\n\nAhead, there is a small clearing amidst the bubbling pits of lava...",
            "output": "text",
            "synopsis": "[You are surrounded by brimstone, lava, and elementals.]"
        },
        "goal_next": {
            "text": "Again, you have invaded %ns domain."
        }
    },
    "Pri": {
        "firsttime": {
            "text": "You find yourself standing in sight of %H.  Something\nis obviously wrong here.  The doors to %H, which usually\nstand open, are closed.  Strange human shapes shamble around\noutside.\n\nYou realize that %l needs your assistance!",
            "output": "text",
            "synopsis": "[You are at %H; the doors are closed.  %lC needs your help!]"
        },
        "nexttime": {
            "text": "Once again, you stand before %H."
        },
        "othertime": {
            "text": "Again you face %H.  Your intuition hints that this may be\nthe final time you come here."
        },
        "locate_first": {
            "text": "You stand facing a large graveyard.  The sky above is filled with clouds\nthat seem to get thicker closer to the center.  You sense the presence of\nundead in larger numbers than you have ever encountered before.\n\nYou remember the descriptions of %i, given to you by\n%l.  It is ahead that you will find %ns trail.",
            "output": "text",
            "synopsis": "[You have found %i.  The trail to %n lies ahead.]"
        },
        "locate_next": {
            "text": "Again, you stand before %i."
        },
        "goal_first": {
            "text": "The stench of brimstone is all about you, and the shrieks and moans\nof tortured souls assault your psyche.\n\nAhead, there is a small clearing amidst the bubbling pits of lava...",
            "output": "text",
            "synopsis": "[The stench of brimstone surrounds you, the shrieks and moans are endless.]"
        },
        "goal_next": {
            "text": "Again, you have invaded %ns domain."
        }
    },
    "Ran": {
        "firsttime": {
            "text": "You arrive in familiar surroundings.  In the distance, you %x the\nancient forest grove, the place of worship to %d.\n\nSomething is wrong, though.  Surrounding the grove are centaurs!\nAnd they've noticed you!",
            "output": "text",
            "synopsis": "[The ancient forest grove is surrounded by centaurs.]"
        },
        "nexttime": {
            "text": "Once again, you stand before %H."
        },
        "othertime": {
            "text": "You have the oddest feeling that this may be the last time you\nare to enter %H."
        },
        "locate_first": {
            "text": "This must be %i.\n\nYou are in a cave built of many different rooms, all interconnected\nby tunnels.  Your quest is to find and shoot the evil wumpus that\nresides elsewhere in the cave without running into any bottomless\npits or using up your limited supply of arrows.  Good luck.\n\nYou are in room 9 of the cave.  There are tunnels to rooms\n5, 8, and 10.\n*rustle* *rustle* (must be bats nearby.)\n*sniff* (I can smell the evil wumpus nearby!)",
            "output": "text",
            "synopsis": "[This is %i.  There are bats nearby.  Beware the wumpus!]"
        },
        "locate_next": {
            "text": "Once again, you descend into %i.\n\n*whoosh* (I feel a draft from some pits.)\n*rustle* *rustle* (must be bats nearby.)",
            "output": "text",
            "synopsis": "[You are in %i.  There are pits.  There are bats nearby.]"
        },
        "goal_first": {
            "text": "You descend into a weird place, in which roughly cut cave-like walls\njoin with smooth, finished ones, as if someone was in the midst of\nfinishing off the construction of a subterranean complex.\n\nOff in the distance, you hear a sound like the clattering of many\nhooves on rock.",
            "output": "text",
            "synopsis": "[You descend into a subterranean complex.  Hooves clatter in the distance.]"
        },
        "goal_next": {
            "text": "Once again, you enter the distorted castle of %n."
        }
    },
    "Rog": {
        "firsttime": {
            "text": "Unexpectedly, you find yourself back in Ransmannsby, where you trained to\nbe a thief.  Quickly you make the guild sign, hoping that you AND word\nof your arrival reach %ls den.",
            "output": "text",
            "synopsis": "[You are in Ransmannsby, where you trained.  Find %l.]"
        },
        "nexttime": {
            "text": "Once again, you find yourself back in Ransmannsby.  Fond memories are\nreplaced by fear, knowing that %l is waiting for you."
        },
        "othertime": {
            "text": "You rub your hands through your hair, hoping that the little ones on\nthe back of your neck stay down, and prepare yourself for your meeting\nwith %l."
        },
        "locate_first": {
            "text": "Those damn little hairs tell you that you are nearer to %o."
        },
        "locate_next": {
            "text": "Not wanting to face %l without having stolen %o, you continue."
        },
        "goal_first": {
            "text": "You feel a great swelling up of courage, sensing the presence of\n%o.  Or is it fear?",
            "output": "text",
            "synopsis": "[You sense %o.]"
        },
        "goal_next": {
            "text": "The hairs on the back of your neck whisper -- it's fear."
        }
    },
    "Sam": {
        "firsttime": {
            "text": "Even before your senses adjust, you recognize the kami of\n%H.\n\nYou %x the standard of your teki, %n, flying above\nthe town.  How could such a thing have happened?  Why are ninja\nwandering freely; where are the samurai of your daimyo, %l?\n\nYou quickly say a prayer to Izanagi and Izanami and walk towards\ntown.",
            "output": "text",
            "synopsis": "[The banner of %n flies above town.  What has happened to %l?]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\n\nInstantly you sense a subtle change in your karma.  You seem to know that\nif you do not succeed in your quest, %n will have destroyed\nthe kami of %H before you return again.",
            "output": "text",
            "synopsis": "[%HC is threatened by %n.]"
        },
        "locate_first": {
            "text": "You instinctively reach for your swords.  You do not recognize the\nlay of this land, but you know that your teki are everywhere."
        },
        "locate_next": {
            "text": "Thankful that your %sp at %H cannot see\nyour fear, you prepare again to advance."
        },
        "goal_first": {
            "text": "In your mind, you hear the taunts of %n.\n\nYou become like the rice plant and bend to the ground, offering a\nprayer to %d.  But when the wind has passed, you stand\nproudly again.  Putting your kami in the hands of fate, you advance.",
            "output": "text",
            "synopsis": "[You feel the taunts %n, but after offering a prayer to %d, you proceed.]"
        },
        "goal_next": {
            "text": "As you arrive once again at the home of %n, your thoughts\nturn only to %o."
        },
        "goal_alt": {
            "text": "As you arrive once again at the home of %n."
        }
    },
    "Tou": {
        "firsttime": {
            "text": "You breathe a sigh of relief as you find yourself back in the familiar\nsurroundings of %H.\n\nYou quickly notice that things do not appear the way they did when you\nleft.  The town is dark and quiet.  There are no sounds coming from\nbehind the town walls, and no campfires burning in the fields.  As a\nmatter of fact, you do not %x any movement in the fields at all, and\nthe crops seem as though they have been untended for many weeks.",
            "output": "text",
            "synopsis": "[You find yourself back at %H, but the quiet is ominous.]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\nThings appear to have become so bad that you fear that soon\n%H will not be here to return to."
        },
        "locate_first": {
            "text": "Only your faith in %d keeps you from trembling.  You %x\nthe handiwork of %ns henchlings everywhere.",
            "output": "text",
            "synopsis": "[You %x the handiwork of %ns henchlings.]"
        },
        "locate_next": {
            "text": "You know that this time you must find and destroy %n."
        },
        "goal_first": {
            "text": "You sense the presence of %o."
        },
        "goal_next": {
            "text": "You gain confidence, knowing that you may soon be united with\n%o."
        },
        "goal_alt": {
            "text": "You have returned to %ns lair."
        }
    },
    "Val": {
        "firsttime": {
            "text": "You materialize at the base of a snowy hill.  Atop the hill sits\na place you know well, %H.  You immediately realize\nthat something here is very wrong!\n\nIn places, the snow and ice have been melted into steaming pools of\nwater.  Fumaroles and pools of bubbling lava surround the hill.\nThe stench of sulphur is carried through the air, and you %x creatures\nthat should not be able to live in this environment moving towards you.",
            "output": "text",
            "synopsis": "[You arrive below %H.  Something is wrong; there is lava present.]"
        },
        "nexttime": {
            "text": "Once again, you are near the abode of %l."
        },
        "othertime": {
            "text": "Again you materialize near %ls abode.  You have a nagging feeling\nthat this may be the last time you come here."
        },
        "locate_first": {
            "text": "The ice and snow gives way to a valley floor.  You %x ahead of you\na huge round hill surrounded by pools of lava.  This then is the entrance\nto %i.  It looks like you're not going to get in without\na fight though.",
            "output": "text",
            "synopsis": "[This is the entrance to %i.]"
        },
        "locate_next": {
            "text": "Once again, you stand before the entrance to %i."
        },
        "goal_first": {
            "text": "Through clouds of sulphurous gasses, you %x a rock palisade\nsurrounded with a moat of bubbling lava.  You remember the description\nfrom something that %l said.  This is the lair of %n.",
            "output": "text",
            "synopsis": "[This is the lair of %n.]"
        },
        "goal_next": {
            "text": "Once again, you stand in sight of %ns lair."
        }
    },
    "Wiz": {
        "firsttime": {
            "text": "You are suddenly in familiar surroundings.  You notice what appears to\nbe a large, squat stone structure nearby.  Wait!  That looks like the\ntower of your former teacher, %l.\n\nHowever, things are not the same as when you were last here.  Mists and\nareas of unexplained darkness surround the tower.  There is movement in\nthe shadows.\n\nYour teacher would never allow such unaesthetic forms to surround the\ntower...  unless something were dreadfully wrong!",
            "output": "text",
            "synopsis": "[You have arrived at %ls tower but something is very wrong.]"
        },
        "nexttime": {
            "text": "Once again, you are back at %H."
        },
        "othertime": {
            "text": "You are back at %H.\nYou have an odd feeling this may be the last time you ever come here."
        },
        "locate_first": {
            "text": "Wisps of fog swirl nearby.  You feel that %ns lair is close."
        },
        "locate_next": {
            "text": "You believe that you may once again invade %i."
        },
        "goal_first": {
            "text": "You feel your mentor's presence; perhaps %o is nearby."
        },
        "goal_next": {
            "text": "The aura of %o tingles at the edge of your perception."
        },
        "goal_alt": {
            "text": "You have returned to %ns lair."
        }
    },
    "_fallbacks": {
        "goal_alt": "goal_next"
    }
};

export const QUEST_TEXT_FALLBACKS = {
    "goal_alt": "goal_next"
};
