// Generated by scripts/generate-ran-loca-level.mjs from
// nethack-c/upstream/dat/Ran-loca.lua. Do not edit by hand.

export const RAN_LOCA_LEVEL_MAP = Object.freeze([
    "              .......  .........  .......              ",
    "     ...................       ...................     ",
    "  ....        .......             .......        ....  ",
    "...    .....     .       .....       .     .....    ...",
    ".   .......... .....  ...........  ..... ..........   .",
    ".  ..  ..... ..........  .....  .......... .....  ..  .",
    ".  .     .     .....       .       .....     .     .  .",
    ".  .   .....         .............         .....   .  .",
    ".  .  ................  .......  ................  .  .",
    ".  .   .....            .......            .....   .  .",
    ".  .     .    ......               ......    .     .  .",
    ".  .     ...........   .........   ...........     .  .",
    ".  .          ..........       ..........          .  .",
    ".  ..  .....     .       .....       .     .....  ..  .",
    ".   .......... .....  ...........  ..... ..........   .",
    ".      ..... ..........  .....  .......... .....      .",
    ".        .     .....       .       .....     .        .",
    "...   .......           .......           .......   ...",
    "  ..............     .............     ..............  ",
    "      .......  .......  .......  .......  .......      "
]);

export const RAN_LOCA_OBJECT_COUNT = 8;

export const RAN_LOCA_TRAPS = Object.freeze([
    "spiked pit",
    "spiked pit",
    "teleport",
    "teleport",
    "arrow",
    "arrow"
]);

export const RAN_LOCA_MONSTERS = Object.freeze([
    {
        "id": "wumpus",
        "x": 27,
        "y": 18,
        "peaceful": 0,
        "asleep": 1
    },
    {
        "id": "giant bat",
        "peaceful": 0
    },
    {
        "id": "giant bat",
        "peaceful": 0
    },
    {
        "id": "giant bat",
        "peaceful": 0
    },
    {
        "id": "giant bat",
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "peaceful": 0
    },
    {
        "class": "s",
        "peaceful": 0
    },
    {
        "class": "s",
        "peaceful": 0
    }
]);
