// Generated by scripts/generate-ran-goal-level.mjs from
// nethack-c/upstream/dat/Ran-goal.lua. Do not edit by hand.

export const RAN_GOAL_LEVEL_MAP = Object.freeze([
    "                                                                            ",
    "  ...                                                                  ...  ",
    " .......................................................................... ",
    "  ...                                +                                 ...  ",
    "   .     ............     .......    .                   .......        .   ",
    "   .  .............................  .       ........   .........S..    .   ",
    "   .   ............    .  ......     .       .      .    .......   ..   .   ",
    "   .     .........     .   ....      +       . ...  .               ..  .   ",
    "   .        S          .         .........   .S.    .S...............   .   ",
    "   .  ...   .     ...  .         .........          .                   .   ",
    "   . ........    .....S.+.......+....\\....+........+.                   .   ",
    "   .  ...         ...    S       .........           ..      .....      .   ",
    "   .                    ..       .........            ..      ......    .   ",
    "   .      .......     ...            +       ....    ....    .......... .   ",
    "   . ..............  ..              .      ......  ..  .............   .   ",
    "   .     .............               .     ..........          ......   .   ",
    "  ...                                +                                 ...  ",
    " .......................................................................... ",
    "  ...                                                                  ...  ",
    "                                                                            "
]);

export const RAN_GOAL_OBJECT_CALLS = Object.freeze([
    [
        {
            "id": "bow",
            "x": 37,
            "y": 10,
            "buc": "blessed",
            "spe": 0,
            "name": "The Longbow of Diana"
        }
    ],
    [
        "chest",
        37,
        10
    ],
    [
        {
            "coord": [
                36,
                9
            ]
        }
    ],
    [
        {
            "coord": [
                36,
                10
            ]
        }
    ],
    [
        {
            "coord": [
                36,
                11
            ]
        }
    ],
    [
        {
            "coord": [
                37,
                9
            ]
        }
    ],
    [
        {
            "coord": [
                37,
                11
            ]
        }
    ],
    [
        {
            "coord": [
                38,
                9
            ]
        }
    ],
    [
        {
            "coord": [
                38,
                10
            ]
        }
    ],
    [
        {
            "coord": [
                38,
                11
            ]
        }
    ],
    [],
    [],
    [],
    [],
    []
]);

export const RAN_GOAL_TRAP_COUNT = 6;

export const RAN_GOAL_DOORS = Object.freeze([
    {
        "type": "locked",
        "x": 12,
        "y": 8
    },
    {
        "type": "closed",
        "x": 22,
        "y": 10
    },
    {
        "type": "locked",
        "x": 24,
        "y": 10
    },
    {
        "type": "closed",
        "x": 25,
        "y": 11
    },
    {
        "type": "closed",
        "x": 32,
        "y": 10
    },
    {
        "type": "closed",
        "x": 37,
        "y": 3
    },
    {
        "type": "closed",
        "x": 37,
        "y": 7
    },
    {
        "type": "closed",
        "x": 37,
        "y": 13
    },
    {
        "type": "closed",
        "x": 37,
        "y": 16
    },
    {
        "type": "closed",
        "x": 42,
        "y": 10
    },
    {
        "type": "locked",
        "x": 46,
        "y": 8
    },
    {
        "type": "closed",
        "x": 51,
        "y": 10
    },
    {
        "type": "locked",
        "x": 53,
        "y": 8
    },
    {
        "type": "closed",
        "x": 65,
        "y": 5
    }
]);

export const RAN_GOAL_MONSTERS = Object.freeze([
    {
        "id": "Scorpius",
        "x": 37,
        "y": 10,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "x": 36,
        "y": 9,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "x": 36,
        "y": 10,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "x": 36,
        "y": 11,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "x": 37,
        "y": 9,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "x": 37,
        "y": 11,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "x": 38,
        "y": 9,
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "x": 38,
        "y": 10,
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "x": 38,
        "y": 11,
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "x": 2,
        "y": 2,
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "x": 71,
        "y": 2,
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "x": 2,
        "y": 16,
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "x": 71,
        "y": 16,
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "peaceful": 0
    },
    {
        "id": "forest centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "id": "mountain centaur",
        "peaceful": 0
    },
    {
        "class": "C",
        "peaceful": 0
    },
    {
        "class": "C",
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "x": 3,
        "y": 2,
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "x": 72,
        "y": 2,
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "x": 3,
        "y": 17,
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "x": 72,
        "y": 17,
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "x": 41,
        "y": 10,
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "x": 33,
        "y": 9,
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "peaceful": 0
    },
    {
        "id": "scorpion",
        "peaceful": 0
    },
    {
        "class": "s",
        "peaceful": 0
    }
]);
