// Rumor diagnostics and Oracle consultation. C refs: rumors.c init_rumors(),
// rumor_check(), others_check(), init_oracles(), outoracle(),
// doconsult(), and the Oracle-state persistence fields. Random-access rumor
// selection and outrumor() remain in the existing random_text.js group.
import {
    ACH_ORCL, A_WIS, BOGUSMONFILE, BUFSZ, BY_ORACLE, COLNO,
    ECMD_OK, ECMD_TIME, ENGRAVEFILE, EPITAPHFILE, ORACLEFILE, RUMORFILE,
} from './const.js';
import { exercise } from './attrib.js';
import { yn_function, y_n } from './cmd.js';
import { capitalizedMonsterName } from './do_name.js';
import { more_experienced, newexplevel } from './exper.js';
import { game } from './gstate.js';
import { record_achievement } from './insight.js';
import { currency, money_cnt } from './invent.js';
import { decodeUtf8ByteString, xcrypt } from './hacklib.js';
import { outrumor } from './random_text.js';
import { RANDOM_TEXT_FILES } from './random_text_data.js';
import { rnd } from './rng.js';
import { money2mon } from './shk.js';
import { displayTtyTextWindow } from './tty_menu.js';
import { displayPendingTtyMessageWindow, ttyPline } from './tty_message.js';
import { note_unported } from './unported.js';

// dlb_fgets over the generated byte file. The cursor is a local file handle;
// persistent offsets stay in the corresponding gt/gf/svo source fields.
function byteLine(file, size) {
    if (file.position >= file.data.length) return null;
    const limit = Math.min(file.data.length, file.position + size - 1);
    const newline = file.data.indexOf('\n', file.position);
    const end = newline >= file.position && newline < limit ? newline + 1 : limit;
    const line = file.data.slice(file.position, end);
    file.position = end;
    return line;
}

// The recorder uses LP64: offsets scanned with %lx are unsigned 64-bit,
// while sizes/ends and explicit (long) casts are signed. Keep ordinary file
// offsets as Numbers and retain values outside their exact range as BigInts
// in the same source field, rather than rounding an unsigned negative token.
function longInteger(value, unsigned = false) {
    const integer = unsigned ? BigInt.asUintN(64, BigInt(value))
        : BigInt.asIntN(64, BigInt(value));
    return integer >= BigInt(Number.MIN_SAFE_INTEGER)
        && integer <= BigInt(Number.MAX_SAFE_INTEGER) ? Number(integer) : integer;
}

// C ref: rumors.c init_rumors() (85-107). Counts and EOF are parsed but local;
// only C's gt/gf offsets persist. A failed init closes its local dlb handle.
export function init_rumors(file, state = game) {
    state.gt ??= {};
    state.gf ??= {};
    byteLine(file, BUFSZ); // Skip makedefs' generated-file comment.
    let remaining = byteLine(file, BUFSZ) ?? '';
    const fields = [
        [null, 'decimal', ','],
        [state.gt, 'decimal', ',', 'true_rumor_size'],
        [state.gt, 'hex', ';', 'true_rumor_start'],
        [null, 'decimal', ','],
        [state.gf, 'decimal', ',', 'false_rumor_size'],
        [state.gf, 'hex', ';0,0,', 'false_rumor_start'],
        [null, 'hex', ''],
    ];
    let converted = 0;
    for (const [owner, kind, separator, field] of fields) {
        // sscanf skips leading whitespace for every numeric conversion.
        const match = remaining.match(kind === 'decimal'
            ? /^\s*[+-]?\d+/u : /^\s*[+-]?(?:0x)?[\da-f]+/iu);
        if (!match) break;
        const token = match[0].trim();
        const negative = token.startsWith('-');
        const digits = token.replace(/^[+-]/u, '').replace(/^0x/iu, '');
        const value = kind === 'decimal' ? longInteger(token)
            : longInteger((negative ? -1n : 1n) * BigInt('0x' + digits), true);
        if (owner) owner[field] = value;
        converted++;
        remaining = remaining.slice(match[0].length);
        if (!remaining.startsWith(separator)) break;
        remaining = remaining.slice(separator.length);
    }
    if (converted === 7 && state.gt.true_rumor_size > 0
        && state.gf.false_rumor_size > 0) {
        state.gt.true_rumor_end = longInteger(BigInt(longInteger(state.gt.true_rumor_start))
            + BigInt(state.gt.true_rumor_size));
        state.gf.false_rumor_end = longInteger(BigInt(longInteger(state.gf.false_rumor_start))
            + BigInt(state.gf.false_rumor_size));
    } else {
        state.gt.true_rumor_size = -1;
        file.closed = true;
    }
}

function decodedLine(line) {
    const newline = line.indexOf('\n');
    const encrypted = newline >= 0 ? line.slice(0, newline) : line;
    return decodeUtf8ByteString(Array.from(xcrypt(encrypted), character => character.charCodeAt(0)));
}

// C ref: rumors.c rumor_check() (196-303). A local line array represents the
// lazily created text window; the tty owner displays and destroys it once.
export async function rumor_check(state = game, env = {}) {
    state.gt ??= {};
    state.gf ??= {};
    state.gt.true_rumor_size ??= 0;
    const files = env.files ?? RANDOM_TEXT_FILES;
    const data = state.gt.true_rumor_size >= 0 ? files[RUMORFILE] : null;
    let file = typeof data === 'string' ? { data, position: 0 } : null;
    const win = { lines: null };
    if (file && state.gt.true_rumor_size === 0) {
        init_rumors(file, state);
        if (state.gt.true_rumor_size < 0) file = null;
    }
    if (file) {
        win.lines = [];
        const decimal = value => {
            const signed = BigInt.asIntN(64, BigInt(value));
            return signed < 0n ? '-' + (-signed).toString().padStart(5, '0')
                : signed.toString().padStart(6, '0');
        };
        const hex = value => BigInt.asUintN(64, BigInt(value)).toString(16).padStart(6, '0');
        for (const [tag, fields, prefix] of [
            ['T', state.gt, 'true_rumor'], ['F', state.gf, 'false_rumor'],
        ]) {
            const start = fields[prefix + '_start'];
            const end = fields[prefix + '_end'];
            const size = fields[prefix + '_size'];
            win.lines.push({ text: tag + ' start=' + decimal(start) + ' (' + hex(start)
                + '), end=' + decimal(end) + ' (' + hex(end)
                + '), size=' + decimal(size) + ' (' + hex(size) + ')' });
        }
        for (const [tag, start, end] of [
            ['T', state.gt.true_rumor_start, state.gt.true_rumor_end],
            ['F', state.gf.false_rumor_start, state.gf.false_rumor_end],
        ]) {
            // The UNIX recorder disables DLB (config.h): dlb_fseek is fseek.
            // A negative signed SEEK_SET offset fails, leaving ftell unchanged.
            const signedStart = Number(longInteger(start));
            if (signedStart >= 0) file.position = signedStart;
            const actualStart = file.position;
            let line = byteLine(file, BUFSZ) ?? '';
            win.lines.push({ text: tag + ' ' + decimal(actualStart) + ' ' + decodedLine(line) });
            // fgets changes line before ftell is compared. The record ending
            // exactly at end is the final displayed line, without unpadline.
            let next;
            while ((next = byteLine(file, BUFSZ)) !== null) {
                line = next;
                if (file.position >= end) break;
            }
            win.lines.push({ text: '         ' + decodedLine(line) });
        }
        file.closed = true;
    } else if (state.gt.true_rumor_size < 0) {
        await (env.message ?? ttyPline)('rumors not accessible.', state);
        await (env.displayMessage ?? displayPendingTtyMessageWindow)(state);
    } else {
        note_unported('rumors.c couldnt_open_file');
        state.gt.true_rumor_size = -1;
    }
    others_check('Engravings:', ENGRAVEFILE, win, env);
    others_check('Epitaphs:', EPITAPHFILE, win, env);
    others_check('Bogus monsters:', BOGUSMONFILE, win, env);
    if (win.lines !== null)
        await (env.window ?? displayTtyTextWindow)(state, win.lines);
}

// C ref: rumors.c others_check() (308-408). The reference tty allocator
// panics before returning WIN_ERR (wintty.c:858-863); JavaScript allocation
// likewise cannot return a recoverable failed window. Missing files retain
// the discarded couldnt_open_file gap; diagnostic records remain raw padded.
export function others_check(ftype, fname, win, env = {}) {
    const data = (env.files ?? RANDOM_TEXT_FILES)[fname];
    if (typeof data !== 'string') {
        note_unported('rumors.c couldnt_open_file');
        return;
    }
    win.lines ??= [];
    const put = text => win.lines.push({ text });
    const error = text => put('others_check("' + fname + '"): ' + text);
    const file = { data, position: 0 };
    put('');
    put(ftype);
    let line = byteLine(file, BUFSZ);
    if (line === null) {
        error("error; can't read comment line");
    } else if (!line.startsWith('#')) {
        error('malformed; first line is not a comment line:');
        const raw = line.split('\n')[0];
        put('- first line, as is');
        put(decodeUtf8ByteString(Array.from(raw, character => character.charCodeAt(0))));
        put('- xcrypt of first line');
        put(decodedLine(line));
    } else {
        line = byteLine(file, BUFSZ);
        if (line === null || line.startsWith('\n')) {
            error(line === null ? "can't read first non-comment line"
                : 'first non-comment line is empty');
        } else {
            put(decodedLine(line));
            line = byteLine(file, BUFSZ);
            if (line === null) {
                put('(no second entry)');
            } else {
                let entrycount = 2;
                let last = decodedLine(line);
                put(last);
                while ((line = byteLine(file, BUFSZ)) !== null) {
                    ++entrycount;
                    last = decodedLine(line);
                }
                if (entrycount === 2) put('(only two entries)');
                else {
                    if (entrycount > 3) put(' ...');
                    put(last);
                }
            }
        }
    }
    file.closed = true;
}

// C ref: rumors.c init_oracles() (577-595). Only called for a fresh data file.
export function init_oracles(file, state = game) {
    byteLine(file, BUFSZ); // Skip makedefs' generated-file comment.
    const countLine = byteLine(file, BUFSZ) ?? '';
    const count = parseInt(countLine.trimStart().slice(0, 5), 10);
    if (count > 0) {
        state.svo.oracle_cnt = count;
        state.svo.oracle_loc = new Array(count);
        for (let i = 0; i < count; i++) {
            const line = byteLine(file, BUFSZ) ?? '';
            state.svo.oracle_loc[i] = parseInt(line.trimStart().slice(0, 5), 16);
        }
    }
}

// C ref: rumors.c save_oracles() (598-620), writing the count and remaining
// offsets only. JSON replaces Sfo_* writes. The FREEING/shutdown branch is
// outside this bounded persistence wiring and receives no completion credit.
export function save_oracles(snapshot, state = game) {
    const count = state.svo?.oracle_cnt ?? 0;
    snapshot.oracles = {
        oracle_cnt: count,
        oracle_loc: count ? state.svo.oracle_loc.slice(0, count) : null,
    };
}

// C ref: rumors.c restore_oracles() (623-637), the selected Oracle-state
// fields in a fresh process. No other restore.c reconstruction belongs here.
export function restore_oracles(snapshot, state = game) {
    state.svo ??= {};
    state.go ??= {};
    state.svo.oracle_cnt = snapshot.oracles?.oracle_cnt ?? 0;
    state.svo.oracle_loc = null;
    state.go.oracle_flg = 0; // decl.c's initial flag, not serialized by C.
    if (state.svo.oracle_cnt) {
        state.svo.oracle_loc = snapshot.oracles.oracle_loc.slice(0, state.svo.oracle_cnt);
        state.go.oracle_flg = 1;
    }
}

// C ref: rumors.c outoracle() (640-694). Generated data replaces dlb's
// open/seek/close; the canonical text window owns output and input boundaries.
export async function outoracle(special, delphi, state = game, env = {}) {
    state.go ??= {};
    state.svo ??= {};
    state.go.oracle_flg ??= 0;
    state.svo.oracle_cnt ??= 0;
    state.svo.oracle_loc ??= null;
    if (state.go.oracle_flg < 0
        || (state.go.oracle_flg > 0 && state.svo.oracle_cnt === 0)) return;

    const data = (env.files ?? RANDOM_TEXT_FILES)[ORACLEFILE];
    if (typeof data !== 'string') {
        note_unported('rumors.c couldnt_open_file');
        state.go.oracle_flg = -1;
        return;
    }
    const file = { data, position: 0 };
    if (state.go.oracle_flg === 0) {
        init_oracles(file, state);
        state.go.oracle_flg = 1;
        if (state.svo.oracle_cnt === 0) return;
    }
    if (state.svo.oracle_cnt <= 1 && !special) return;
    const oracle_idx = special ? 0 : (env.random?.rnd ?? rnd)(state.svo.oracle_cnt - 1);
    file.position = state.svo.oracle_loc[oracle_idx];
    if (!special)
        state.svo.oracle_loc[oracle_idx] = state.svo.oracle_loc[--state.svo.oracle_cnt];

    const lines = [{ text: delphi
        ? special ? 'The Oracle scornfully takes all your gold and says:'
            : 'The Oracle meditates for a moment and then intones:'
        : 'The message reads:' }, { text: '' }];
    let line;
    while ((line = byteLine(file, COLNO)) !== null && line !== '---\n') {
        const newline = line.indexOf('\n');
        if (newline >= 0) line = line.slice(0, newline);
        lines.push({ text: xcrypt(line) });
    }
    await (env.window ?? displayTtyTextWindow)(state, lines);
}

// C ref: rumors.c doconsult() (696-769).
export async function doconsult(oracl, state = game, env = {}) {
    const message = env.message ?? ttyPline;
    const minor_cost = 50;
    const major_cost = 500 + 50 * state.u.ulevel;
    state.multi = 0;
    const umoney = money_cnt(state.invent);

    if (!oracl) {
        await message('There is no one here to consult.', state);
        return ECMD_OK;
    } else if (!oracl.mpeaceful) {
        await message(`${capitalizedMonsterName(oracl, state)} is in no mood for consultations.`, state);
        return ECMD_OK;
    } else if (!umoney) {
        await message('You have no gold.', state);
        return ECMD_OK;
    }

    let qbuf = `"Wilt thou settle for a minor consultation?" (${minor_cost} ${currency(minor_cost, state, env)})`;
    // hack.h ynq() records the answer for repeat, with 'q' as its default.
    const answer = env.ynq
        ? await env.ynq(qbuf, state)
        : await yn_function(qbuf, 'ynq', 'q', true, state);
    let u_pay;
    switch (answer) {
    default:
    case 0x71: // C 'q'; yn_function returns a response byte.
        return ECMD_OK;
    case 0x79: // C 'y'.
        if (umoney < minor_cost) {
            await message("You don't even have enough gold for that!", state);
            return ECMD_OK;
        }
        u_pay = minor_cost;
        break;
    case 0x6e: // C 'n'.
        // C decl.c initializes go.oracle_flg and svo.oracle_cnt to zero.
        if (umoney <= minor_cost || state.svo?.oracle_cnt === 1
            || (state.go?.oracle_flg ?? 0) < 0)
            return ECMD_OK;
        qbuf = `"Then dost thou desire a major one?" (${major_cost} ${currency(major_cost, state, env)})`;
        if (await (env.y_n ?? y_n)(qbuf, state) !== 0x79)
            return ECMD_OK;
        u_pay = Math.min(umoney, major_cost);
        break;
    }
    money2mon(oracl, u_pay, state);
    state.disp.botl = true;
    const event = state.u.uevent;
    if (!event.major_oracle && !event.minor_oracle)
        record_achievement(ACH_ORCL, state);
    let add_xpts = 0;
    if (u_pay === minor_cost) {
        await outrumor(1, BY_ORACLE, state, env);
        if (!event.minor_oracle)
            add_xpts = Math.trunc(u_pay / (event.major_oracle ? 25 : 10));
        event.minor_oracle = true;
    } else {
        const cheapskate = u_pay < major_cost;
        await outoracle(cheapskate, true, state, env);
        if (!cheapskate && !event.major_oracle)
            add_xpts = Math.trunc(u_pay / (event.minor_oracle ? 25 : 10));
        event.major_oracle = true;
        await exercise(A_WIS, !cheapskate, state, env.random);
    }
    if (add_xpts) {
        more_experienced(add_xpts, Math.trunc(u_pay / 50), state);
        await newexplevel(state, { ...env, message });
    }
    return ECMD_TIME;
}
