// Oracle consultation. C refs: rumors.c init_oracles(), outoracle(),
// doconsult(), and the Oracle-state persistence fields. Random-access rumor
// selection and outrumor() remain in the existing random_text.js group.
import { ACH_ORCL, A_WIS, BUFSZ, BY_ORACLE, COLNO, ECMD_OK, ECMD_TIME, ORACLEFILE } from './const.js';
import { exercise } from './attrib.js';
import { yn_function, y_n } from './cmd.js';
import { capitalizedMonsterName } from './do_name.js';
import { more_experienced, newexplevel } from './exper.js';
import { game } from './gstate.js';
import { record_achievement } from './insight.js';
import { currency, money_cnt } from './invent.js';
import { xcrypt } from './hacklib.js';
import { outrumor } from './random_text.js';
import { RANDOM_TEXT_FILES } from './random_text_data.js';
import { rnd } from './rng.js';
import { money2mon } from './shk.js';
import { displayTtyTextWindow } from './tty_menu.js';
import { ttyPline } from './tty_message.js';
import { note_unported } from './unported.js';

// dlb_fgets over the generated byte file. The cursor is a local file handle;
// persistent offsets stay exclusively in C's svo.oracle_loc.
function oracleLine(file, size) {
    if (file.position >= file.data.length) return null;
    const limit = Math.min(file.data.length, file.position + size - 1);
    const newline = file.data.indexOf('\n', file.position);
    const end = newline >= file.position && newline < limit ? newline + 1 : limit;
    const line = file.data.slice(file.position, end);
    file.position = end;
    return line;
}

// C ref: rumors.c init_oracles() (577-595). Only called for a fresh data file.
export function init_oracles(file, state = game) {
    oracleLine(file, BUFSZ); // Skip makedefs' generated-file comment.
    const countLine = oracleLine(file, BUFSZ) ?? '';
    const count = parseInt(countLine.trimStart().slice(0, 5), 10);
    if (count > 0) {
        state.svo.oracle_cnt = count;
        state.svo.oracle_loc = new Array(count);
        for (let i = 0; i < count; i++) {
            const line = oracleLine(file, BUFSZ) ?? '';
            state.svo.oracle_loc[i] = parseInt(line.trimStart().slice(0, 5), 16);
        }
    }
}

// C ref: rumors.c save_oracles() (598-620), writing the count and remaining
// offsets only. JSON replaces Sfo_* writes. The FREEING/shutdown branch is
// outside this bounded persistence wiring and receives no completion credit.
export function save_oracles(snapshot, state = game) {
    const count = state.svo?.oracle_cnt ?? 0;
    snapshot.oracles = {
        oracle_cnt: count,
        oracle_loc: count ? state.svo.oracle_loc.slice(0, count) : null,
    };
}

// C ref: rumors.c restore_oracles() (623-637), the selected Oracle-state
// fields in a fresh process. No other restore.c reconstruction belongs here.
export function restore_oracles(snapshot, state = game) {
    state.svo ??= {};
    state.go ??= {};
    state.svo.oracle_cnt = snapshot.oracles?.oracle_cnt ?? 0;
    state.svo.oracle_loc = null;
    state.go.oracle_flg = 0; // decl.c's initial flag, not serialized by C.
    if (state.svo.oracle_cnt) {
        state.svo.oracle_loc = snapshot.oracles.oracle_loc.slice(0, state.svo.oracle_cnt);
        state.go.oracle_flg = 1;
    }
}

// C ref: rumors.c outoracle() (640-694). Generated data replaces dlb's
// open/seek/close; the canonical text window owns output and input boundaries.
export async function outoracle(special, delphi, state = game, env = {}) {
    state.go ??= {};
    state.svo ??= {};
    state.go.oracle_flg ??= 0;
    state.svo.oracle_cnt ??= 0;
    state.svo.oracle_loc ??= null;
    if (state.go.oracle_flg < 0
        || (state.go.oracle_flg > 0 && state.svo.oracle_cnt === 0)) return;

    const data = (env.files ?? RANDOM_TEXT_FILES)[ORACLEFILE];
    if (typeof data !== 'string') {
        note_unported('rumors.c couldnt_open_file');
        state.go.oracle_flg = -1;
        return;
    }
    const file = { data, position: 0 };
    if (state.go.oracle_flg === 0) {
        init_oracles(file, state);
        state.go.oracle_flg = 1;
        if (state.svo.oracle_cnt === 0) return;
    }
    if (state.svo.oracle_cnt <= 1 && !special) return;
    const oracle_idx = special ? 0 : (env.random?.rnd ?? rnd)(state.svo.oracle_cnt - 1);
    file.position = state.svo.oracle_loc[oracle_idx];
    if (!special)
        state.svo.oracle_loc[oracle_idx] = state.svo.oracle_loc[--state.svo.oracle_cnt];

    const lines = [{ text: delphi
        ? special ? 'The Oracle scornfully takes all your gold and says:'
            : 'The Oracle meditates for a moment and then intones:'
        : 'The message reads:' }, { text: '' }];
    let line;
    while ((line = oracleLine(file, COLNO)) !== null && line !== '---\n') {
        const newline = line.indexOf('\n');
        if (newline >= 0) line = line.slice(0, newline);
        lines.push({ text: xcrypt(line) });
    }
    await (env.window ?? displayTtyTextWindow)(state, lines);
}

// C ref: rumors.c doconsult() (696-769).
export async function doconsult(oracl, state = game, env = {}) {
    const message = env.message ?? ttyPline;
    const minor_cost = 50;
    const major_cost = 500 + 50 * state.u.ulevel;
    state.multi = 0;
    const umoney = money_cnt(state.invent);

    if (!oracl) {
        await message('There is no one here to consult.', state);
        return ECMD_OK;
    } else if (!oracl.mpeaceful) {
        await message(`${capitalizedMonsterName(oracl, state)} is in no mood for consultations.`, state);
        return ECMD_OK;
    } else if (!umoney) {
        await message('You have no gold.', state);
        return ECMD_OK;
    }

    let qbuf = `"Wilt thou settle for a minor consultation?" (${minor_cost} ${currency(minor_cost, state, env)})`;
    // hack.h ynq() records the answer for repeat, with 'q' as its default.
    const answer = env.ynq
        ? await env.ynq(qbuf, state)
        : await yn_function(qbuf, 'ynq', 'q', true, state);
    let u_pay;
    switch (answer) {
    default:
    case 0x71: // C 'q'; yn_function returns a response byte.
        return ECMD_OK;
    case 0x79: // C 'y'.
        if (umoney < minor_cost) {
            await message("You don't even have enough gold for that!", state);
            return ECMD_OK;
        }
        u_pay = minor_cost;
        break;
    case 0x6e: // C 'n'.
        // C decl.c initializes go.oracle_flg and svo.oracle_cnt to zero.
        if (umoney <= minor_cost || state.svo?.oracle_cnt === 1
            || (state.go?.oracle_flg ?? 0) < 0)
            return ECMD_OK;
        qbuf = `"Then dost thou desire a major one?" (${major_cost} ${currency(major_cost, state, env)})`;
        if (await (env.y_n ?? y_n)(qbuf, state) !== 0x79)
            return ECMD_OK;
        u_pay = Math.min(umoney, major_cost);
        break;
    }
    money2mon(oracl, u_pay, state);
    state.disp.botl = true;
    const event = state.u.uevent;
    if (!event.major_oracle && !event.minor_oracle)
        record_achievement(ACH_ORCL, state);
    let add_xpts = 0;
    if (u_pay === minor_cost) {
        await outrumor(1, BY_ORACLE, state, env);
        if (!event.minor_oracle)
            add_xpts = Math.trunc(u_pay / (event.major_oracle ? 25 : 10));
        event.minor_oracle = true;
    } else {
        const cheapskate = u_pay < major_cost;
        await outoracle(cheapskate, true, state, env);
        if (!cheapskate && !event.major_oracle)
            add_xpts = Math.trunc(u_pay / (event.minor_oracle ? 25 : 10));
        event.major_oracle = true;
        await exercise(A_WIS, !cheapskate, state, env.random);
    }
    if (add_xpts) {
        more_experienced(add_xpts, Math.trunc(u_pay / 50), state);
        await newexplevel(state, { ...env, message });
    }
    return ECMD_TIME;
}
