// Generated by scripts/generate-status-field-data.mjs from botl.c.
export const STATUS_FIELDS = Object.freeze([
    {
        "name": "title",
        "key": "title",
        "type": 15,
        "fld": 0,
        "idxmax": -1
    },
    {
        "name": "strength",
        "key": "strength",
        "type": 4,
        "fld": 1,
        "idxmax": -1
    },
    {
        "name": "dexterity",
        "key": "dexterity",
        "type": 4,
        "fld": 2,
        "idxmax": -1
    },
    {
        "name": "constitution",
        "key": "constitution",
        "type": 4,
        "fld": 3,
        "idxmax": -1
    },
    {
        "name": "intelligence",
        "key": "intelligence",
        "type": 4,
        "fld": 4,
        "idxmax": -1
    },
    {
        "name": "wisdom",
        "key": "wisdom",
        "type": 4,
        "fld": 5,
        "idxmax": -1
    },
    {
        "name": "charisma",
        "key": "charisma",
        "type": 4,
        "fld": 6,
        "idxmax": -1
    },
    {
        "name": "alignment",
        "key": "alignment",
        "type": 15,
        "fld": 7,
        "idxmax": -1
    },
    {
        "name": "score",
        "key": "score",
        "type": 9,
        "fld": 8,
        "idxmax": -1
    },
    {
        "name": "carrying-capacity",
        "key": "carrying-capacity",
        "type": 4,
        "fld": 9,
        "idxmax": -1
    },
    {
        "name": "gold",
        "key": "gold",
        "type": 9,
        "fld": 10,
        "idxmax": -1
    },
    {
        "name": "power",
        "key": "power",
        "type": 4,
        "fld": 11,
        "idxmax": 12
    },
    {
        "name": "power-max",
        "key": "power-max",
        "type": 4,
        "fld": 12,
        "idxmax": -1
    },
    {
        "name": "experience-level",
        "key": "experience-level",
        "type": 4,
        "fld": 13,
        "idxmax": 21
    },
    {
        "name": "armor-class",
        "key": "armor-class",
        "type": 4,
        "fld": 14,
        "idxmax": -1
    },
    {
        "name": "HD",
        "key": "hd",
        "type": 4,
        "fld": 15,
        "idxmax": -1
    },
    {
        "name": "time",
        "key": "time",
        "type": 9,
        "fld": 16,
        "idxmax": -1
    },
    {
        "name": "hunger",
        "key": "hunger",
        "type": 4,
        "fld": 17,
        "idxmax": -1
    },
    {
        "name": "hitpoints",
        "key": "hitpoints",
        "type": 4,
        "fld": 18,
        "idxmax": 19
    },
    {
        "name": "hitpoints-max",
        "key": "hitpoints-max",
        "type": 4,
        "fld": 19,
        "idxmax": -1
    },
    {
        "name": "dungeon-level",
        "key": "dungeon-level",
        "type": 15,
        "fld": 20,
        "idxmax": -1
    },
    {
        "name": "experience",
        "key": "experience",
        "type": 9,
        "fld": 21,
        "idxmax": 21
    },
    {
        "name": "condition",
        "key": "condition",
        "type": 17,
        "fld": 22,
        "idxmax": -1
    },
    {
        "name": "version",
        "key": "version",
        "type": 15,
        "fld": 26,
        "idxmax": -1
    },
    {
        "name": "weapon",
        "key": "weapon",
        "type": 15,
        "fld": 23,
        "idxmax": -1
    },
    {
        "name": "armor",
        "key": "armor",
        "type": 15,
        "fld": 24,
        "idxmax": -1
    },
    {
        "name": "terrain",
        "key": "terrain",
        "type": 15,
        "fld": 25,
        "idxmax": -1
    }
].map(Object.freeze));

export const STATUS_CONDITIONS = Object.freeze([
    {
        "mask": 1,
        "text": "Bare",
        "option": "barehanded"
    },
    {
        "mask": 2,
        "text": "Blind",
        "option": "blind"
    },
    {
        "mask": 4,
        "text": "Busy",
        "option": "busy"
    },
    {
        "mask": 8,
        "text": "Conf",
        "option": "conf"
    },
    {
        "mask": 16,
        "text": "Deaf",
        "option": "deaf"
    },
    {
        "mask": 32,
        "text": "Iron",
        "option": "iron"
    },
    {
        "mask": 64,
        "text": "Fly",
        "option": "fly"
    },
    {
        "mask": 128,
        "text": "FoodPois",
        "option": "foodpois"
    },
    {
        "mask": 256,
        "text": "Glow",
        "option": "glowhands"
    },
    {
        "mask": 512,
        "text": "Grab",
        "option": "grab"
    },
    {
        "mask": 1024,
        "text": "Hallu",
        "option": "hallucinat"
    },
    {
        "mask": 2048,
        "text": "Held",
        "option": "held"
    },
    {
        "mask": 4096,
        "text": "Icy",
        "option": "ice"
    },
    {
        "mask": 8192,
        "text": "InLava",
        "option": "lava"
    },
    {
        "mask": 16384,
        "text": "Lev",
        "option": "levitate"
    },
    {
        "mask": 32768,
        "text": "Parlyz",
        "option": "paralyzed"
    },
    {
        "mask": 65536,
        "text": "Ride",
        "option": "ride"
    },
    {
        "mask": 131072,
        "text": "Zzz",
        "option": "sleep"
    },
    {
        "mask": 262144,
        "text": "Slime",
        "option": "slime"
    },
    {
        "mask": 524288,
        "text": "Slip",
        "option": "slip"
    },
    {
        "mask": 1048576,
        "text": "Stone",
        "option": "stone"
    },
    {
        "mask": 2097152,
        "text": "Strngl",
        "option": "strngl"
    },
    {
        "mask": 4194304,
        "text": "Stun",
        "option": "stun"
    },
    {
        "mask": 8388608,
        "text": "Submrg",
        "option": "submerged"
    },
    {
        "mask": 16777216,
        "text": "TermIll",
        "option": "termill"
    },
    {
        "mask": 33554432,
        "text": "Teth",
        "option": "tethered"
    },
    {
        "mask": 67108864,
        "text": "Trap",
        "option": "trap"
    },
    {
        "mask": 134217728,
        "text": "Out",
        "option": "unconscious"
    },
    {
        "mask": 268435456,
        "text": "WLegs",
        "option": "woundedlegs"
    },
    {
        "mask": 536870912,
        "text": "UHold",
        "option": "holding"
    }
].map(Object.freeze));

export const STATUS_CONDITION_ALIASES = Object.freeze([
    {
        "name": "strangled",
        "mask": 2097152
    },
    {
        "name": "all",
        "mask": 1073741823
    },
    {
        "name": "major_troubles",
        "mask": 20193920
    },
    {
        "name": "minor_troubles",
        "mask": 12616730
    },
    {
        "name": "movement",
        "mask": 81984
    },
    {
        "name": "opt_in",
        "mask": 1049270533
    }
].map(Object.freeze));
