// Generated by scripts/generate-themeroom-data.mjs.
// Source: nethack-c/upstream/dat/themerms.lua at 16ff59115315917b93185d026aeefea06db9b0f4.

function freezeDefinition(definition) {
    if (definition.map) Object.freeze(definition.map);
    if (definition.filler) Object.freeze(definition.filler);
    return Object.freeze(definition);
}

export const THEMEROOM_DEFINITIONS = Object.freeze(
    [
        {
            "name": "default",
            "frequency": 1000,
            "sourceLine": 283,
            "sourceKind": "room"
        },
        {
            "name": "Fake Delphi",
            "frequency": 1,
            "sourceLine": 291,
            "sourceKind": "room"
        },
        {
            "name": "Room in a room",
            "frequency": 1,
            "sourceLine": 307,
            "sourceKind": "room"
        },
        {
            "name": "Huge room with another room inside",
            "frequency": 1,
            "sourceLine": 322,
            "sourceKind": "room"
        },
        {
            "name": "Nesting rooms",
            "frequency": 1,
            "sourceLine": 343,
            "sourceKind": "room"
        },
        {
            "name": "Default room with themed fill",
            "frequency": 6,
            "sourceLine": 375,
            "sourceKind": "room"
        },
        {
            "name": "Unlit room with themed fill",
            "frequency": 2,
            "sourceLine": 383,
            "sourceKind": "room"
        },
        {
            "name": "Room with both normal contents and themed fill",
            "frequency": 2,
            "sourceLine": 391,
            "sourceKind": "room"
        },
        {
            "name": "Pillars",
            "frequency": 1,
            "sourceLine": 399,
            "sourceKind": "room"
        },
        {
            "name": "Mausoleum",
            "frequency": 1,
            "sourceLine": 419,
            "sourceKind": "room"
        },
        {
            "name": "Random dungeon feature in the middle of an odd-sized room",
            "frequency": 1,
            "sourceLine": 445,
            "sourceKind": "room"
        },
        {
            "name": "L-shaped",
            "frequency": 1,
            "sourceLine": 461,
            "sourceKind": "map",
            "map": [
                "-----xxx",
                "|...|xxx",
                "|...|xxx",
                "|...----",
                "|......|",
                "|......|",
                "|......|",
                "--------"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 1,
                "y": 1
            }
        },
        {
            "name": "L-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 476,
            "sourceKind": "map",
            "map": [
                "xxx-----",
                "xxx|...|",
                "xxx|...|",
                "----...|",
                "|......|",
                "|......|",
                "|......|",
                "--------"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 5,
                "y": 1
            }
        },
        {
            "name": "L-shaped, rot 2",
            "frequency": 1,
            "sourceLine": 491,
            "sourceKind": "map",
            "map": [
                "--------",
                "|......|",
                "|......|",
                "|......|",
                "----...|",
                "xxx|...|",
                "xxx|...|",
                "xxx-----"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 1,
                "y": 1
            }
        },
        {
            "name": "L-shaped, rot 3",
            "frequency": 1,
            "sourceLine": 506,
            "sourceKind": "map",
            "map": [
                "--------",
                "|......|",
                "|......|",
                "|......|",
                "|...----",
                "|...|xxx",
                "|...|xxx",
                "-----xxx"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 1,
                "y": 1
            }
        },
        {
            "name": "Blocked center",
            "frequency": 1,
            "sourceLine": 521,
            "sourceKind": "map"
        },
        {
            "name": "Circular, small",
            "frequency": 1,
            "sourceLine": 548,
            "sourceKind": "map",
            "map": [
                "xx---xx",
                "x--.--x",
                "--...--",
                "|.....|",
                "--...--",
                "x--.--x",
                "xx---xx"
            ],
            "width": 7,
            "height": 7,
            "filler": {
                "x": 3,
                "y": 3
            }
        },
        {
            "name": "Circular, medium",
            "frequency": 1,
            "sourceLine": 562,
            "sourceKind": "map",
            "map": [
                "xx-----xx",
                "x--...--x",
                "--.....--",
                "|.......|",
                "|.......|",
                "|.......|",
                "--.....--",
                "x--...--x",
                "xx-----xx"
            ],
            "width": 9,
            "height": 9,
            "filler": {
                "x": 4,
                "y": 4
            }
        },
        {
            "name": "Circular, big",
            "frequency": 1,
            "sourceLine": 578,
            "sourceKind": "map",
            "map": [
                "xxx-----xxx",
                "x---...---x",
                "x-.......-x",
                "--.......--",
                "|.........|",
                "|.........|",
                "|.........|",
                "--.......--",
                "x-.......-x",
                "x---...---x",
                "xxx-----xxx"
            ],
            "width": 11,
            "height": 11,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "name": "T-shaped",
            "frequency": 1,
            "sourceLine": 596,
            "sourceKind": "map",
            "map": [
                "xxx-----xxx",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "----...----",
                "|.........|",
                "|.........|",
                "|.........|",
                "-----------"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "name": "T-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 611,
            "sourceKind": "map",
            "map": [
                "-----xxx",
                "|...|xxx",
                "|...|xxx",
                "|...----",
                "|......|",
                "|......|",
                "|......|",
                "|...----",
                "|...|xxx",
                "|...|xxx",
                "-----xxx"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "name": "T-shaped, rot 2",
            "frequency": 1,
            "sourceLine": 629,
            "sourceKind": "map",
            "map": [
                "-----------",
                "|.........|",
                "|.........|",
                "|.........|",
                "----...----",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "xxx-----xxx"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "name": "T-shaped, rot 3",
            "frequency": 1,
            "sourceLine": 644,
            "sourceKind": "map",
            "map": [
                "xxx-----",
                "xxx|...|",
                "xxx|...|",
                "----...|",
                "|......|",
                "|......|",
                "|......|",
                "----...|",
                "xxx|...|",
                "xxx|...|",
                "xxx-----"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "name": "S-shaped",
            "frequency": 1,
            "sourceLine": 662,
            "sourceKind": "map",
            "map": [
                "-----xxx",
                "|...|xxx",
                "|...|xxx",
                "|...----",
                "|......|",
                "|......|",
                "|......|",
                "----...|",
                "xxx|...|",
                "xxx|...|",
                "xxx-----"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "name": "S-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 680,
            "sourceKind": "map",
            "map": [
                "xxx--------",
                "xxx|......|",
                "xxx|......|",
                "----......|",
                "|......----",
                "|......|xxx",
                "|......|xxx",
                "--------xxx"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "name": "Z-shaped",
            "frequency": 1,
            "sourceLine": 695,
            "sourceKind": "map",
            "map": [
                "xxx-----",
                "xxx|...|",
                "xxx|...|",
                "----...|",
                "|......|",
                "|......|",
                "|......|",
                "|...----",
                "|...|xxx",
                "|...|xxx",
                "-----xxx"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "name": "Z-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 713,
            "sourceKind": "map",
            "map": [
                "--------xxx",
                "|......|xxx",
                "|......|xxx",
                "|......----",
                "----......|",
                "xxx|......|",
                "xxx|......|",
                "xxx--------"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "name": "Cross",
            "frequency": 1,
            "sourceLine": 728,
            "sourceKind": "map",
            "map": [
                "xxx-----xxx",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "----...----",
                "|.........|",
                "|.........|",
                "|.........|",
                "----...----",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "xxx-----xxx"
            ],
            "width": 11,
            "height": 11,
            "filler": {
                "x": 6,
                "y": 6
            }
        },
        {
            "name": "Four-leaf clover",
            "frequency": 1,
            "sourceLine": 746,
            "sourceKind": "map",
            "map": [
                "-----x-----",
                "|...|x|...|",
                "|...---...|",
                "|.........|",
                "---.....---",
                "xx|.....|xx",
                "---.....---",
                "|.........|",
                "|...---...|",
                "|...|x|...|",
                "-----x-----"
            ],
            "width": 11,
            "height": 11,
            "filler": {
                "x": 6,
                "y": 6
            }
        },
        {
            "name": "Water-surrounded vault",
            "frequency": 1,
            "sourceLine": 764,
            "sourceKind": "map"
        },
        {
            "name": "Twin businesses",
            "frequency": 1,
            "sourceLine": 817,
            "mindiff": 4,
            "sourceKind": "room"
        }
    ].map(freezeDefinition),
);
