// Generated by scripts/generate-themeroom-data.mjs.
// Source: nethack-c/upstream/dat/themerms.lua at 16ff59115315917b93185d026aeefea06db9b0f4.

// sourceLine is the Lua table entry's opening line. action is a closed,
// source-derived description of how its contents callback is dispatched.

function deepFreeze(value) {
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    for (const nested of Object.values(value)) deepFreeze(nested);
    return Object.freeze(value);
}

export const THEMEROOM_DEFINITIONS = Object.freeze(
    [
        {
            "id": "default",
            "name": "default",
            "frequency": 1000,
            "sourceLine": 283,
            "sourceKind": "room",
            "action": {
                "kind": "room",
                "room": {
                    "type": "ordinary",
                    "filled": 1
                }
            }
        },
        {
            "id": "fake-delphi",
            "name": "Fake Delphi",
            "frequency": 1,
            "sourceLine": 291,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "fake-delphi"
            }
        },
        {
            "id": "room-in-a-room",
            "name": "Room in a room",
            "frequency": 1,
            "sourceLine": 307,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "room-in-a-room"
            }
        },
        {
            "id": "huge-room-with-another-room-inside",
            "name": "Huge room with another room inside",
            "frequency": 1,
            "sourceLine": 322,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "huge-room-with-another-room-inside"
            }
        },
        {
            "id": "nesting-rooms",
            "name": "Nesting rooms",
            "frequency": 1,
            "sourceLine": 343,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "nesting-rooms"
            }
        },
        {
            "id": "default-room-with-themed-fill",
            "name": "Default room with themed fill",
            "frequency": 6,
            "sourceLine": 375,
            "sourceKind": "room",
            "action": {
                "kind": "room",
                "room": {
                    "type": "themed"
                },
                "contents": {
                    "kind": "themeroom-fill"
                }
            }
        },
        {
            "id": "unlit-room-with-themed-fill",
            "name": "Unlit room with themed fill",
            "frequency": 2,
            "sourceLine": 383,
            "sourceKind": "room",
            "action": {
                "kind": "room",
                "room": {
                    "type": "themed",
                    "lit": 0
                },
                "contents": {
                    "kind": "themeroom-fill"
                }
            }
        },
        {
            "id": "room-with-both-normal-contents-and-themed-fill",
            "name": "Room with both normal contents and themed fill",
            "frequency": 2,
            "sourceLine": 391,
            "sourceKind": "room",
            "action": {
                "kind": "room",
                "room": {
                    "type": "themed",
                    "filled": 1
                },
                "contents": {
                    "kind": "themeroom-fill"
                }
            }
        },
        {
            "id": "pillars",
            "name": "Pillars",
            "frequency": 1,
            "sourceLine": 399,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "pillars"
            }
        },
        {
            "id": "mausoleum",
            "name": "Mausoleum",
            "frequency": 1,
            "sourceLine": 419,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "mausoleum"
            }
        },
        {
            "id": "random-dungeon-feature-in-the-middle-of-an-odd-sized-room",
            "name": "Random dungeon feature in the middle of an odd-sized room",
            "frequency": 1,
            "sourceLine": 445,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "random-dungeon-feature-in-the-middle-of-an-odd-sized-room"
            }
        },
        {
            "id": "l-shaped",
            "name": "L-shaped",
            "frequency": 1,
            "sourceLine": 461,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 1,
                        "y": 1
                    }
                }
            },
            "map": [
                "-----xxx",
                "|...|xxx",
                "|...|xxx",
                "|...----",
                "|......|",
                "|......|",
                "|......|",
                "--------"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 1,
                "y": 1
            }
        },
        {
            "id": "l-shaped-rot-1",
            "name": "L-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 476,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 5,
                        "y": 1
                    }
                }
            },
            "map": [
                "xxx-----",
                "xxx|...|",
                "xxx|...|",
                "----...|",
                "|......|",
                "|......|",
                "|......|",
                "--------"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 5,
                "y": 1
            }
        },
        {
            "id": "l-shaped-rot-2",
            "name": "L-shaped, rot 2",
            "frequency": 1,
            "sourceLine": 491,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 1,
                        "y": 1
                    }
                }
            },
            "map": [
                "--------",
                "|......|",
                "|......|",
                "|......|",
                "----...|",
                "xxx|...|",
                "xxx|...|",
                "xxx-----"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 1,
                "y": 1
            }
        },
        {
            "id": "l-shaped-rot-3",
            "name": "L-shaped, rot 3",
            "frequency": 1,
            "sourceLine": 506,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 1,
                        "y": 1
                    }
                }
            },
            "map": [
                "--------",
                "|......|",
                "|......|",
                "|......|",
                "|...----",
                "|...|xxx",
                "|...|xxx",
                "-----xxx"
            ],
            "width": 8,
            "height": 8,
            "filler": {
                "x": 1,
                "y": 1
            }
        },
        {
            "id": "blocked-center",
            "name": "Blocked center",
            "frequency": 1,
            "sourceLine": 521,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "handler",
                    "handler": "blocked-center",
                    "filler": {
                        "x": 1,
                        "y": 1
                    }
                }
            },
            "map": [
                "-----------",
                "|.........|",
                "|.........|",
                "|.........|",
                "|...LLL...|",
                "|...LLL...|",
                "|...LLL...|",
                "|.........|",
                "|.........|",
                "|.........|",
                "-----------"
            ],
            "width": 11,
            "height": 11
        },
        {
            "id": "circular-small",
            "name": "Circular, small",
            "frequency": 1,
            "sourceLine": 548,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 3,
                        "y": 3
                    }
                }
            },
            "map": [
                "xx---xx",
                "x--.--x",
                "--...--",
                "|.....|",
                "--...--",
                "x--.--x",
                "xx---xx"
            ],
            "width": 7,
            "height": 7,
            "filler": {
                "x": 3,
                "y": 3
            }
        },
        {
            "id": "circular-medium",
            "name": "Circular, medium",
            "frequency": 1,
            "sourceLine": 562,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 4,
                        "y": 4
                    }
                }
            },
            "map": [
                "xx-----xx",
                "x--...--x",
                "--.....--",
                "|.......|",
                "|.......|",
                "|.......|",
                "--.....--",
                "x--...--x",
                "xx-----xx"
            ],
            "width": 9,
            "height": 9,
            "filler": {
                "x": 4,
                "y": 4
            }
        },
        {
            "id": "circular-big",
            "name": "Circular, big",
            "frequency": 1,
            "sourceLine": 578,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 5,
                        "y": 5
                    }
                }
            },
            "map": [
                "xxx-----xxx",
                "x---...---x",
                "x-.......-x",
                "--.......--",
                "|.........|",
                "|.........|",
                "|.........|",
                "--.......--",
                "x-.......-x",
                "x---...---x",
                "xxx-----xxx"
            ],
            "width": 11,
            "height": 11,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "id": "t-shaped",
            "name": "T-shaped",
            "frequency": 1,
            "sourceLine": 596,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 5,
                        "y": 5
                    }
                }
            },
            "map": [
                "xxx-----xxx",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "----...----",
                "|.........|",
                "|.........|",
                "|.........|",
                "-----------"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "id": "t-shaped-rot-1",
            "name": "T-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 611,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 2,
                        "y": 2
                    }
                }
            },
            "map": [
                "-----xxx",
                "|...|xxx",
                "|...|xxx",
                "|...----",
                "|......|",
                "|......|",
                "|......|",
                "|...----",
                "|...|xxx",
                "|...|xxx",
                "-----xxx"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "id": "t-shaped-rot-2",
            "name": "T-shaped, rot 2",
            "frequency": 1,
            "sourceLine": 629,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 2,
                        "y": 2
                    }
                }
            },
            "map": [
                "-----------",
                "|.........|",
                "|.........|",
                "|.........|",
                "----...----",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "xxx-----xxx"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "id": "t-shaped-rot-3",
            "name": "T-shaped, rot 3",
            "frequency": 1,
            "sourceLine": 644,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 5,
                        "y": 5
                    }
                }
            },
            "map": [
                "xxx-----",
                "xxx|...|",
                "xxx|...|",
                "----...|",
                "|......|",
                "|......|",
                "|......|",
                "----...|",
                "xxx|...|",
                "xxx|...|",
                "xxx-----"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "id": "s-shaped",
            "name": "S-shaped",
            "frequency": 1,
            "sourceLine": 662,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 2,
                        "y": 2
                    }
                }
            },
            "map": [
                "-----xxx",
                "|...|xxx",
                "|...|xxx",
                "|...----",
                "|......|",
                "|......|",
                "|......|",
                "----...|",
                "xxx|...|",
                "xxx|...|",
                "xxx-----"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "id": "s-shaped-rot-1",
            "name": "S-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 680,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 5,
                        "y": 5
                    }
                }
            },
            "map": [
                "xxx--------",
                "xxx|......|",
                "xxx|......|",
                "----......|",
                "|......----",
                "|......|xxx",
                "|......|xxx",
                "--------xxx"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "id": "z-shaped",
            "name": "Z-shaped",
            "frequency": 1,
            "sourceLine": 695,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 5,
                        "y": 5
                    }
                }
            },
            "map": [
                "xxx-----",
                "xxx|...|",
                "xxx|...|",
                "----...|",
                "|......|",
                "|......|",
                "|......|",
                "|...----",
                "|...|xxx",
                "|...|xxx",
                "-----xxx"
            ],
            "width": 8,
            "height": 11,
            "filler": {
                "x": 5,
                "y": 5
            }
        },
        {
            "id": "z-shaped-rot-1",
            "name": "Z-shaped, rot 1",
            "frequency": 1,
            "sourceLine": 713,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 2,
                        "y": 2
                    }
                }
            },
            "map": [
                "--------xxx",
                "|......|xxx",
                "|......|xxx",
                "|......----",
                "----......|",
                "xxx|......|",
                "xxx|......|",
                "xxx--------"
            ],
            "width": 11,
            "height": 8,
            "filler": {
                "x": 2,
                "y": 2
            }
        },
        {
            "id": "cross",
            "name": "Cross",
            "frequency": 1,
            "sourceLine": 728,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 6,
                        "y": 6
                    }
                }
            },
            "map": [
                "xxx-----xxx",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "----...----",
                "|.........|",
                "|.........|",
                "|.........|",
                "----...----",
                "xxx|...|xxx",
                "xxx|...|xxx",
                "xxx-----xxx"
            ],
            "width": 11,
            "height": 11,
            "filler": {
                "x": 6,
                "y": 6
            }
        },
        {
            "id": "four-leaf-clover",
            "name": "Four-leaf clover",
            "frequency": 1,
            "sourceLine": 746,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "filler-region",
                    "filler": {
                        "x": 6,
                        "y": 6
                    }
                }
            },
            "map": [
                "-----x-----",
                "|...|x|...|",
                "|...---...|",
                "|.........|",
                "---.....---",
                "xx|.....|xx",
                "---.....---",
                "|.........|",
                "|...---...|",
                "|...|x|...|",
                "-----x-----"
            ],
            "width": 11,
            "height": 11,
            "filler": {
                "x": 6,
                "y": 6
            }
        },
        {
            "id": "water-surrounded-vault",
            "name": "Water-surrounded vault",
            "frequency": 1,
            "sourceLine": 764,
            "sourceKind": "map",
            "action": {
                "kind": "map",
                "contents": {
                    "kind": "handler",
                    "handler": "water-surrounded-vault"
                }
            },
            "map": [
                "}}}}}}",
                "}----}",
                "}|..|}",
                "}|..|}",
                "}----}",
                "}}}}}}"
            ],
            "width": 6,
            "height": 6
        },
        {
            "id": "twin-businesses",
            "name": "Twin businesses",
            "frequency": 1,
            "sourceLine": 817,
            "mindiff": 4,
            "sourceKind": "room",
            "action": {
                "kind": "handler",
                "handler": "twin-businesses"
            }
        }
    ].map(deepFreeze),
);
