// tty_startup.js — TTY banner and player-name prompt used during startup.
// C refs: win/tty/wintty.c tty_init_nhwindows(), tty_askname();
// sys/unix/sysconf GENERICUSERS; patch 001's deterministic build banner.

import { PL_NSIZ } from './const.js';
import { game } from './gstate.js';
import { nhgetch } from './input.js';
import { plnamesuffix } from './role_init.js';
import { NO_COLOR } from './terminal.js';

const WHO_ARE_YOU = 'Who are you? ';
const GENERIC_USERS = new Set([
    'play',
    'player',
    'game',
    'games',
    'nethack',
    'nethacker',
    'ec2-user',
]);

// The first, second, and fourth lines come from include/patchlevel.h. The
// third is generated by makedefs; recorder patch 001 pins its build clock.
export const TTY_STARTUP_BANNER = Object.freeze([
    'NetHack, Copyright 1985-2026',
    '         By Stichting Mathematisch Centrum and M. Stephenson.',
    '         Version 5.0.0 Unix, built May  2 2026 12:00:00.',
    '         See license for details.',
]);

export function renderTtyStartupBanner(state = game) {
    const display = state.nhDisplay;
    if (!display) return;

    display.clearScreen();
    for (let i = 0; i < TTY_STARTUP_BANNER.length; i++) {
        display.putstr(0, 4 + i, TTY_STARTUP_BANNER[i], NO_COLOR);
    }
    // tty_init_nhwindows() leaves BASE_WINDOW at (1, 11); tty_askname()
    // emits one empty base-window line before placing its prompt on row 12.
    display.setCursor(0, 11);
    state._ttyBaseCursorRow = 11;
}

export function isGenericPlayerName(name, plnamelen = 0) {
    const text = String(name ?? '');
    const suffix = text.indexOf('-', plnamelen);
    const candidate = text.slice(0, suffix < 0 ? text.length : suffix);
    // hacklib.c findword(..., FALSE) is case-sensitive here.
    return GENERIC_USERS.has(candidate);
}

function ttyNameCharacter(code, length) {
    const ch = String.fromCharCode(code & 0xFF);
    if (ch === '-' || ch === '@'
        || (ch >= 'a' && ch <= 'z')
        || (ch >= 'A' && ch <= 'Z')
        || (length > 0 && ch >= '0' && ch <= '9')) {
        return ch;
    }
    return '_';
}

// C ref: win/tty/wintty.c tty_askname(). This is deliberately a tty input
// loop rather than a generic text field: each nhgetch() is a judge-visible
// boundary, and the Unix character filtering and echo order are observable.
export async function ttyAskname(state = game) {
    const display = state.nhDisplay;
    if (!display) throw new Error('tty_askname requires an initialized display');

    // The initial empty tty_putstr() advances BASE_WINDOW one row on every
    // invocation. That is observable when plnamesuffix() strips a suffix-only
    // name and calls askname again; the retry counter itself is per-call.
    const entryRow = state._ttyBaseCursorRow ?? display.cursorRow;
    const promptRow = entryRow + 1;
    state._ttyBaseCursorRow = promptRow;
    let tryct = 0;
    for (;;) {
        tryct++;
        if (tryct > 10) throw new Error('Giving up after 10 tries.');

        if (tryct > 1) {
            display.setCursor(0, promptRow - 1);
            display.putstr(
                0,
                promptRow - 1,
                'Enter a name for your character...',
                NO_COLOR,
            );
            display.clearRow(promptRow);
        }

        display.putstr(0, promptRow, WHO_ARE_YOU, NO_COLOR);
        display.setCursor(WHO_ARE_YOU.length, promptRow);

        const characters = [];
        let retry = false;
        for (;;) {
            const code = await nhgetch(state);
            if (code === 10 || code === 13) break;
            // tty_nhgetch() translates NUL to Escape before tty_askname().
            if (code === 0 || code === 27) {
                characters.length = 0;
                retry = true;
                break;
            }
            if (code === 8 || code === 127) {
                if (characters.length > 0) {
                    characters.pop();
                    const column = WHO_ARE_YOU.length + characters.length;
                    display.setCell(column, promptRow, ' ', NO_COLOR);
                    display.setCursor(column, promptRow);
                }
                continue;
            }

            const ch = ttyNameCharacter(code, characters.length);
            if (characters.length < PL_NSIZ - 1) {
                characters.push(ch);
                display.setCell(
                    display.cursorCol,
                    display.cursorRow,
                    ch,
                    NO_COLOR,
                );
                display.setCursor(display.cursorCol + 1, display.cursorRow);
            }
        }

        if (!retry && characters.length > 0) {
            state.plname = characters.join('');
            state._ttyBaseCursorRow = promptRow + 1;
            display.setCursor(0, promptRow + 1);
            state.iflags ??= {};
            state.iflags.renameallowed = true;
            return state.plname;
        }
    }
}

export async function ensureTtyPlayerName(state = game) {
    const plnamelen = state.gp?.plnamelen ?? 0;
    if (isGenericPlayerName(state.plname, plnamelen)) {
        state.plname = '';
        if (state.gp) state.gp.plnamelen = 0;
    }
    if (!state.plname) {
        await ttyAskname(state);
        if (state.gp) state.gp.plnamelen = 0;
    }
    return state.plname;
}

// C ref: role.c plnamesuffix(). A name can consist only of suffix tokens
// (for example, "-Wizard"); stripping those leaves an empty base and C loops
// straight back through askname while retaining the parsed selections.
export async function ttyPlayerNameAndSuffix(state = game) {
    do {
        await ensureTtyPlayerName(state);
        plnamesuffix(state);
    } while (!state.plname);
    return state.plname;
}
