// Generated by scripts/generate-val-loca-level.mjs from
// nethack-c/upstream/dat/Val-loca.lua. Do not edit by hand.

export const VAL_LOCA_LEVEL_MAP = Object.freeze([
    "PPPPxxxx                      xxxxPPPPPx",
    "PLPxxx                          xPPLLLPP",
    "PPP    .......................    PPPLLP",
    "xx   ............................   PPPP",
    "x  ...............................  xxxx",
    "  .................................   xx",
    "....................................   x",
    "  ...................................   ",
    "x  ..................................  x",
    "xx   ..............................   PP",
    "xPPP  ..........................     PLP",
    "xPLLP                             xxPLLP",
    "xPPPPxx                         xxxxPPPP"
]);
