// Generated by scripts/generate-val-goal-level.mjs from
// nethack-c/upstream/dat/Val-goal.lua. Do not edit by hand.

export const VAL_GOAL_LEVEL_MAP = Object.freeze([
    "xxxxxx.....................xxxxxxxx",
    "xxxxx.......LLLLL.LLLLL......xxxxxx",
    "xxxx......LLLLLLLLLLLLLLL......xxxx",
    "xxxx.....LLL|---------|LLL.....xxxx",
    "xxxx....LL|--.........--|LL.....xxx",
    "x......LL|-...LLLLLLL...-|LL.....xx",
    ".......LL|...LL.....LL...|LL......x",
    "......LL|-..LL.......LL..-|LL......",
    "......LL|.................|LL......",
    "......LL|-..LL.......LL..-|LL......",
    ".......LL|...LL.....LL...|LL.......",
    "xx.....LL|-...LLLLLLL...-|LL......x",
    "xxx.....LL|--.........--|LL.....xxx",
    "xxxx.....LLL|---------|LLL...xxxxxx",
    "xxxxx.....LLLLLLLLLLLLLLL...xxxxxxx",
    "xxxxxx......LLLLL.LLLLL.....xxxxxxx",
    "xxxxxxxxx..................xxxxxxxx"
]);

export const VAL_GOAL_OBJECT_CALLS = Object.freeze([
    [
        {
            "id": "crystal ball",
            "x": 17,
            "y": 8,
            "buc": "blessed",
            "spe": 5,
            "name": "The Orb of Fate"
        }
    ],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
]);

export const VAL_GOAL_TRAPS = Object.freeze([
    [
        "board",
        13,
        8
    ],
    [
        "board",
        21,
        8
    ],
    [
        "fire"
    ],
    [
        "fire"
    ],
    [
        "fire"
    ],
    [
        "fire"
    ],
    [
        "board"
    ],
    [],
    []
]);

export const VAL_GOAL_MONSTERS = Object.freeze([
    [
        "Lord Surtur",
        17,
        8
    ],
    [
        "fire ant"
    ],
    [
        "fire ant"
    ],
    [
        "fire ant"
    ],
    [
        "fire ant"
    ],
    [
        "a"
    ],
    [
        "a"
    ],
    [
        {
            "id": "fire giant",
            "x": 10,
            "y": 6,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 10,
            "y": 7,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 10,
            "y": 8,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 10,
            "y": 9,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 10,
            "y": 10,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 24,
            "y": 6,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 24,
            "y": 7,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 24,
            "y": 8,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 24,
            "y": 9,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "x": 24,
            "y": 10,
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "peaceful": 0
        }
    ],
    [
        {
            "id": "fire giant",
            "peaceful": 0
        }
    ],
    [
        {
            "class": "H",
            "peaceful": 0
        }
    ]
]);

export const VAL_GOAL_DRAWBRIDGES = Object.freeze([
    {
        "x": 17,
        "y": 2,
        "dir": "south",
        "state": "random"
    },
    {
        "x": 17,
        "y": 14,
        "dir": "north",
        "state": "open"
    },
    {
        "x": 17,
        "y": 14,
        "dir": "north",
        "state": "random"
    }
]);
