// Generated by scripts/generate-wizcmds-memory-layout.mjs.
// C refs: NetHack 16ff59115315917b93185d026aeefea06db9b0f4; headers and worm.c struct wseg; LP64 ABI.
export const memoryLayout = Object.freeze({
    "obj": 112,
    "oextra": 32,
    "monst": 192,
    "mextra": 64,
    "egd": 640,
    "epri": 56,
    "eshk": 4960,
    "emin": 8,
    "edog": 64,
    "ebones": 28,
    "wseg": 16,
    "trap": 32,
    "engr": 64,
    "damage": 32,
    "kinfo": 272,
    "cemetery": 184,
    "light_source": 32,
    "timer_element": 48,
    "NhRegion": 96,
    "NhRect": 8,
    "unsigned": 4,
    "mapseen": 384
});
