#!/usr/bin/env node

// Generate the nasties[] table from wizard.c. pick_nasty() (wizard.c:536-581)
// rolls a random entry from this 44-element static array when creating nasty
// monsters for the Wizard's harassment or for sandestin shapeshifting.
//
// The table is small, but AGENTS.md requires generation for any fixed table
// copied from C source.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const UPSTREAM_ROOT = join(PROJECT_ROOT, 'nethack-c', 'upstream');
const SOURCE_PATH = join(UPSTREAM_ROOT, 'src', 'wizard.c');
const OUTPUT_PATH = join(PROJECT_ROOT, 'js', 'nasties_data.js');
const PINNED_REVISION = '16ff59115315917b93185d026aeefea06db9b0f4';

// Parse the nasties[] initializer from wizard.c. The table starts with
// "static NEARDATA const int nasties[] = {" and ends at the next "};".
export function parseNasties(source) {
    const lines = source.split('\n');
    let inside = false;
    const entries = [];
    for (const line of lines) {
        if (!inside) {
            if (/^\s*static\s+NEARDATA\s+const\s+int\s+nasties\[\]\s*=\s*\{/u
                .test(line)) {
                inside = true;
                // The opening line itself may contain entries after the brace.
                const afterBrace = line.slice(line.indexOf('{') + 1);
                extractPMs(afterBrace, entries);
            }
            continue;
        }
        if (line.includes('};')) break;
        extractPMs(line, entries);
    }
    if (!inside) throw new Error('nasties[] not found in wizard.c');
    if (entries.length === 0) throw new Error('nasties[] is empty');
    return entries;
}

// Extract PM_* identifiers from a line, ignoring comments.
function extractPMs(line, out) {
    // Strip C comments (/* ... */) from the line.
    const stripped = line.replace(/\/\*.*?\*\//gu, '');
    for (const match of stripped.matchAll(/PM_[A-Z_]+/gu)) {
        out.push(match[0]);
    }
}

export function renderNastiesData(entries) {
    const imports = entries.map((e) => `    ${e},`).join('\n');
    const items = entries.map((e) => `    ${e},`).join('\n');
    return (
        '// Generated by scripts/generate-nasties.mjs.\n'
        + `// Source: NetHack 5.0 src/wizard.c at ${PINNED_REVISION}.\n`
        + '// Do not edit this file by hand.\n\n'
        + 'import {\n'
        + imports + '\n'
        + "} from './monsters.js';\n\n"
        + '// C ref: wizard.c:31-50, nasties[].\n'
        + 'export const NASTIES = Object.freeze([\n'
        + items + '\n'
        + ']);\n'
    );
}

function assertPinnedSource() {
    const revision = execFileSync(
        'git', ['-C', UPSTREAM_ROOT, 'rev-parse', 'HEAD'], { encoding: 'utf8' },
    ).trim();
    if (revision !== PINNED_REVISION) {
        throw new Error(
            `expected NetHack source ${PINNED_REVISION}; found ${revision}`,
        );
    }
    const status = execFileSync(
        'git', [
            '-C', UPSTREAM_ROOT, 'status', '--porcelain=v1',
            '--untracked-files=no',
        ],
        { encoding: 'utf8' },
    ).trim();
    if (status)
        throw new Error('refusing to generate from modified upstream sources');
}

function main() {
    const checkOnly = process.argv.length === 3
        && process.argv[2] === '--check';
    if (process.argv.length > (checkOnly ? 3 : 2))
        throw new Error(
            'Usage: node scripts/generate-nasties.mjs [--check]',
        );

    assertPinnedSource();
    const output = renderNastiesData(
        parseNasties(readFileSync(SOURCE_PATH, 'utf8')),
    );
    if (checkOnly) {
        let existing = '';
        try {
            existing = readFileSync(OUTPUT_PATH, 'utf8');
        } catch {
            // The comparison below reports the missing generated file.
        }
        if (existing !== output) {
            console.error(
                'js/nasties_data.js is stale; run '
                + 'node scripts/generate-nasties.mjs',
            );
            process.exitCode = 1;
        }
    } else {
        writeFileSync(OUTPUT_PATH, output);
    }
}

if (process.argv[1]
    && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
