import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {QUEST_LEVEL_LOADERS} from '../js/quest_levels.js';
import {VAL_LOCA_LEVEL_MAP} from '../js/val_loca_level_data.js';
import {extractValLocaMap, renderValLocaMap} from './generate-val-loca-level.mjs';

const source = readFileSync('nethack-c/upstream/dat/Val-loca.lua', 'utf8');
test('Val-loca fixed map is generated byte for byte from all source rows', () => {
    const rows = extractValLocaMap(source);
    assert.deepEqual(VAL_LOCA_LEVEL_MAP, rows);
    assert.equal(rows.length, 13); // Source13–25, including the last pool row.
    assert.ok(rows.every(row => row.length === 40)); // Spaces and transparent x cells count.
    assert.equal(readFileSync('js/val_loca_level_data.js', 'utf8'), renderValLocaMap(rows));
});
test('Val-loca translates every top-level descriptor in source order', async () => {
    const calls = [];
    const des = new Proxy({}, {get: (_, name) => async (...args) => calls.push({name, args})});
    assert.equal(typeof QUEST_LEVEL_LOADERS['Val-loca'], 'function');
    await QUEST_LEVEL_LOADERS['Val-loca'](des);
    assert.deepEqual(calls.map(c => c.name), ['level_init', 'level_flags', 'level_init',
        'map', 'region', 'stair', 'stair', 'non_diggable',
        ...Array(15).fill('object'), ...Array(6).fill('trap'), ...Array(27).fill('monster')]);
    // Source6/8/10 preserve initialization and icedpools/noflip before mines.
    assert.deepEqual(calls[0].args, [{style:'solidfill', fg:' '}]);
    assert.deepEqual(calls[1].args, ['mazelevel','hardfloor','icedpools','noflip']);
    assert.deepEqual(calls[2].args, [{style:'mines', fg:'.', bg:'I', smoothed:true,
        joined:false, lit:1, walled:false}]);
    assert.deepEqual(calls[3].args, [VAL_LOCA_LEVEL_MAP]);
    assert.deepEqual(calls[4].args[0].bounds(), {lx:0, ly:0, hx:39, hy:12}); // Source28.
    assert.equal(calls[4].args[1], 'lit');
    assert.deepEqual(calls[5].args, ['up',48,14]); // Source30 deliberately outside fragment.
    assert.deepEqual(calls[6].args, ['down',20,6]); // Source31 inside the map.
    assert.deepEqual(calls[7].args[0].bounds(), {lx:0, ly:0, hx:39, hy:12}); // Source33.
    assert.ok(calls.filter(c=>c.name==='object').every(c=>c.args.length===0)); // Source35–49 random objects.
    assert.deepEqual(calls.filter(c=>c.name==='trap').map(c=>c.args),
        [['fire'],['fire'],['fire'],['fire'],[],[]]); // Source51–56 named then random traps.
    assert.deepEqual(calls.filter(c=>c.name==='monster').map(c=>c.args), [
        ...Array(17).fill(['fire ant']), ['a'], [{class:'H', peaceful:0}],
        ...Array(7).fill([{id:'fire giant', peaceful:0}]), [{class:'H', peaceful:0}],
    ]); // Source58–84: positional ants, hostile class/ID tables and final giant class.
});
